//! SkillCallParser — 在 chat stream 中扫描 `<use_skill>` 闭合。
//!
//! Spec: docs/design/agent-infra-module.md §2 Skill 调用文本协议，§5 SkillCallParser API
//!
//! 规则：
//! - Parser 实时增量扫描 provider stream；不缓冲整 turn。
//! - 检测到 `<use_skill name="X">` 后**只**缓冲到 `</use_skill>` 闭合，期间不 emit text_delta
//!   （避免泄漏 raw XML 给 UI）。
//! - 闭合后解析 JSON：成功 → emit `UseSkill`；失败 → emit `ParseError`。
//! - 嵌套非法（`<use_skill>` 内部又出现 `<use_skill>`）→ `ParseError`。
//! - 流到 turn 结束（`finalize`）仍未闭合的 `<use_skill>` 当 text 处理（不 dispatch）。

use crate::domain::agent::JsonSummary;

/// Parser 事件输出。
#[derive(Debug, Clone, PartialEq)]
pub enum ParserEvent {
    /// 透传给 stream 的文本。
    TextDelta(String),
    /// 检测到一次完整 `<use_skill name="X">{...}</use_skill>`，可 dispatch。
    UseSkill { name: String, input: JsonSummary },
    /// 标签格式 / JSON 解析错误 → caller 应包装为 `<skill_error code="parse_error">` 回给模型。
    ParseError { reason: String, partial: String },
}

/// Parser 状态机：
/// - `Idle`：在普通文本中；检测 `<use_skill` 起手时切到 InOpeningTag。
/// - `InOpeningTag`：累积 opening tag 内容（直到 `>`）。
/// - `InContent`：在 `<use_skill ...>` 和 `</use_skill>` 之间，累积 JSON。
#[derive(Debug, Clone, PartialEq)]
enum State {
    Idle,
    InOpeningTag,
    InContent,
}

const USE_SKILL_OPEN: &str = "<use_skill";
const USE_SKILL_CLOSE: &str = "</use_skill>";

/// SkillCallParser — 增量扫描 chat stream 检测 `<use_skill>` 标签。
pub struct SkillCallParser {
    state: State,
    /// 当前还没决定是文本还是 tag 的字节缓冲（处理 partial chunk）。
    pending: String,
    /// `InContent` 状态下累积的 inner content（不含闭合标签）。
    content_buf: String,
    /// `InOpeningTag` 状态下累积的 opening tag（含 `<use_skill` 前缀）。
    opening_buf: String,
    /// 当前正在解析的 skill name（opening tag 解析出来的）。
    current_name: Option<String>,
}

impl SkillCallParser {
    pub fn new() -> Self {
        Self {
            state: State::Idle,
            pending: String::new(),
            content_buf: String::new(),
            opening_buf: String::new(),
            current_name: None,
        }
    }

    /// Feed a chunk of provider stream text. Returns parser events generated by this chunk.
    pub fn feed(&mut self, chunk: &str) -> Vec<ParserEvent> {
        let mut events: Vec<ParserEvent> = Vec::new();
        self.pending.push_str(chunk);
        self.process(&mut events);
        events
    }

    /// End-of-stream. Flush any pending text. Unclosed tags are treated as plain text.
    pub fn finalize(&mut self) -> Vec<ParserEvent> {
        let mut events: Vec<ParserEvent> = Vec::new();
        // Flush incomplete tags as text per spec.
        match self.state {
            State::Idle => {
                if !self.pending.is_empty() {
                    let text = std::mem::take(&mut self.pending);
                    if !text.is_empty() {
                        events.push(ParserEvent::TextDelta(text));
                    }
                }
            }
            State::InOpeningTag => {
                // Unclosed opening tag → flush as text.
                let mut text = std::mem::take(&mut self.opening_buf);
                text.push_str(&std::mem::take(&mut self.pending));
                events.push(ParserEvent::TextDelta(text));
                self.state = State::Idle;
            }
            State::InContent => {
                // Unclosed: flush opening + content as text.
                let mut text = format!("<use_skill name=\"{}\">", self.current_name.clone().unwrap_or_default());
                text.push_str(&std::mem::take(&mut self.content_buf));
                text.push_str(&std::mem::take(&mut self.pending));
                events.push(ParserEvent::TextDelta(text));
                self.state = State::Idle;
                self.current_name = None;
            }
        }
        events
    }

    fn process(&mut self, events: &mut Vec<ParserEvent>) {
        // Loop until pending no longer changes shape.
        loop {
            let progressed = match self.state {
                State::Idle => self.step_idle(events),
                State::InOpeningTag => self.step_opening(events),
                State::InContent => self.step_content(events),
            };
            if !progressed {
                break;
            }
        }
    }

    /// In Idle state: emit text up to next `<use_skill` (if seen). If partial prefix of `<use_skill`
    /// at end of pending, hold off to wait for more input.
    fn step_idle(&mut self, events: &mut Vec<ParserEvent>) -> bool {
        if let Some(pos) = self.pending.find(USE_SKILL_OPEN) {
            // Emit everything before the tag start as text.
            let prefix: String = self.pending.drain(..pos).collect();
            if !prefix.is_empty() {
                events.push(ParserEvent::TextDelta(prefix));
            }
            // Move USE_SKILL_OPEN ("<use_skill") into opening_buf and advance.
            let head: String = self.pending.drain(..USE_SKILL_OPEN.len()).collect();
            self.opening_buf = head;
            self.state = State::InOpeningTag;
            return true;
        }
        // Tag not found. We may have a partial prefix of `<use_skill` at the end. Keep it pending
        // and flush the safe-text prefix.
        if let Some(safe_end) = safe_emit_idx(&self.pending, USE_SKILL_OPEN) {
            if safe_end > 0 {
                let prefix: String = self.pending.drain(..safe_end).collect();
                if !prefix.is_empty() {
                    events.push(ParserEvent::TextDelta(prefix));
                }
                return true;
            }
        }
        false
    }

    /// Accumulate opening tag bytes until `>` is found. Then parse `name="..."` and switch to
    /// InContent. Disallow nested `<use_skill` inside opening tag.
    fn step_opening(&mut self, events: &mut Vec<ParserEvent>) -> bool {
        // Move bytes from pending to opening_buf until `>` is found, with a safety cap.
        let mut found_gt = None;
        for (i, ch) in self.pending.char_indices() {
            if ch == '>' {
                found_gt = Some(i + ch.len_utf8());
                break;
            }
        }
        let Some(end) = found_gt else {
            // Move everything into opening_buf and wait for more.
            self.opening_buf.push_str(&self.pending);
            self.pending.clear();
            return false;
        };
        let head: String = self.pending.drain(..end).collect();
        self.opening_buf.push_str(&head);
        // self.opening_buf now contains `<use_skill ... >`
        match parse_opening_tag(&self.opening_buf) {
            Ok(name) => {
                self.current_name = Some(name);
                self.opening_buf.clear();
                self.content_buf.clear();
                self.state = State::InContent;
            }
            Err(reason) => {
                let partial = std::mem::take(&mut self.opening_buf);
                events.push(ParserEvent::ParseError { reason, partial });
                self.state = State::Idle;
                self.current_name = None;
            }
        }
        true
    }

    /// Accumulate JSON content until `</use_skill>` or detect nested `<use_skill` (illegal).
    fn step_content(&mut self, events: &mut Vec<ParserEvent>) -> bool {
        // Find the earlier of `</use_skill>` (close) or `<use_skill` (illegal nest).
        let pos_close = self.pending.find(USE_SKILL_CLOSE);
        let pos_nest = self.pending.find(USE_SKILL_OPEN);

        if let (Some(pn), Some(pc)) = (pos_nest, pos_close) {
            // If nest occurs before close: illegal.
            if pn < pc {
                let mut partial = self.content_buf.clone();
                partial.push_str(&self.pending[..=pn]);
                self.content_buf.clear();
                self.pending.clear();
                events.push(ParserEvent::ParseError {
                    reason: "nested <use_skill> not allowed".into(),
                    partial,
                });
                self.state = State::Idle;
                self.current_name = None;
                return true;
            }
        } else if let Some(pn) = pos_nest {
            // Only nest found (no close yet) → illegal.
            let mut partial = self.content_buf.clone();
            partial.push_str(&self.pending[..=pn]);
            self.content_buf.clear();
            self.pending.clear();
            events.push(ParserEvent::ParseError {
                reason: "nested <use_skill> not allowed".into(),
                partial,
            });
            self.state = State::Idle;
            self.current_name = None;
            return true;
        }

        if let Some(pc) = pos_close {
            // Move pending[..pc] into content_buf; consume close tag; parse JSON.
            let inner: String = self.pending.drain(..pc).collect();
            self.content_buf.push_str(&inner);
            // Drop the close tag.
            self.pending.drain(..USE_SKILL_CLOSE.len());
            // Parse JSON
            let raw_inner = std::mem::take(&mut self.content_buf);
            let trimmed = raw_inner.trim();
            let name = self.current_name.take().unwrap_or_default();
            match serde_json::from_str::<JsonSummary>(trimmed) {
                Ok(input) => events.push(ParserEvent::UseSkill { name, input }),
                Err(e) => events.push(ParserEvent::ParseError {
                    reason: format!("invalid JSON in <use_skill>: {}", e),
                    partial: raw_inner,
                }),
            }
            self.state = State::Idle;
            return true;
        }

        // Neither close nor nest found. Keep bytes in content_buf but hold a small tail to handle
        // partial `</use_skill>` or `<use_skill` straddling chunks.
        if let Some(safe_end) = safe_emit_idx(&self.pending, USE_SKILL_CLOSE) {
            let safe_end2 = match safe_emit_idx(&self.pending[..safe_end], USE_SKILL_OPEN) {
                Some(x) => x.min(safe_end),
                None => safe_end,
            };
            if safe_end2 > 0 {
                let chunk: String = self.pending.drain(..safe_end2).collect();
                self.content_buf.push_str(&chunk);
                return true;
            }
        }
        false
    }

}

impl Default for SkillCallParser {
    fn default() -> Self {
        Self::new()
    }
}

/// Compute the largest prefix length we can safely emit as text without risk of having started a tag.
/// Specifically, if the tail of `s` matches a prefix of `marker`, hold those bytes back.
fn safe_emit_idx(s: &str, marker: &str) -> Option<usize> {
    if s.is_empty() {
        return Some(0);
    }
    // Largest k <= s.len() such that s.ends_with(marker[..k]). Then safe_emit = s.len() - k.
    let max_k = s.len().min(marker.len());
    for k in (1..=max_k).rev() {
        if s.is_char_boundary(s.len() - k) {
            let tail = &s[s.len() - k..];
            if let Some(prefix) = marker.get(..k) {
                if tail == prefix {
                    return Some(s.len() - k);
                }
            }
        }
    }
    Some(s.len())
}

/// Parse `<use_skill name="X">` opening tag. Returns the name on success.
fn parse_opening_tag(tag: &str) -> Result<String, String> {
    // Expected shape: `<use_skill name="<name>">` (allow whitespace).
    let tag = tag.trim();
    let stripped = tag
        .strip_prefix(USE_SKILL_OPEN)
        .and_then(|s| s.strip_suffix('>'))
        .ok_or_else(|| "malformed opening tag".to_string())?;
    let stripped = stripped.trim();
    // Find `name=`
    let after_name = stripped
        .strip_prefix("name")
        .ok_or_else(|| "missing name= attribute".to_string())?
        .trim_start();
    let after_eq = after_name
        .strip_prefix('=')
        .ok_or_else(|| "missing = in name attribute".to_string())?
        .trim_start();
    // Quoted value.
    let quote = after_eq
        .chars()
        .next()
        .ok_or_else(|| "missing quoted name value".to_string())?;
    if quote != '"' && quote != '\'' {
        return Err("name attribute must be quoted".into());
    }
    let rest = &after_eq[quote.len_utf8()..];
    let close = rest
        .find(quote)
        .ok_or_else(|| "unterminated quoted name value".to_string())?;
    let name = &rest[..close];
    if name.is_empty() {
        return Err("empty skill name".into());
    }
    Ok(name.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn drain(p: &mut SkillCallParser, chunk: &str) -> Vec<ParserEvent> {
        p.feed(chunk)
    }

    #[test]
    fn t1_plain_text_emits_text_delta() {
        let mut p = SkillCallParser::new();
        let evs = drain(&mut p, "hello world");
        assert_eq!(evs, vec![ParserEvent::TextDelta("hello world".into())]);
    }

    #[test]
    fn t2_single_use_skill_complete_in_one_chunk() {
        let mut p = SkillCallParser::new();
        let evs = drain(
            &mut p,
            r#"before <use_skill name="fetch_quote">{"tsCode":"600519.SH"}</use_skill> after"#,
        );
        // expect: TextDelta("before "), UseSkill, TextDelta(" after")
        let mut iter = evs.into_iter();
        match iter.next().unwrap() {
            ParserEvent::TextDelta(s) => assert_eq!(s, "before "),
            x => panic!("unexpected {:?}", x),
        }
        match iter.next().unwrap() {
            ParserEvent::UseSkill { name, input } => {
                assert_eq!(name, "fetch_quote");
                assert_eq!(input["tsCode"], "600519.SH");
            }
            x => panic!("unexpected {:?}", x),
        }
        match iter.next().unwrap() {
            ParserEvent::TextDelta(s) => assert_eq!(s, " after"),
            x => panic!("unexpected {:?}", x),
        }
    }

    #[test]
    fn t3_chunk_split_in_middle_of_opening_tag() {
        let mut p = SkillCallParser::new();
        let mut evs = vec![];
        evs.extend(p.feed("Hi <use_sk"));
        evs.extend(p.feed("ill name=\"fetch_quote\">{\"a\":1}</use_skill>!"));
        // collect texts and useskill counts
        let mut text = String::new();
        let mut count_use = 0;
        for e in evs {
            match e {
                ParserEvent::TextDelta(s) => text.push_str(&s),
                ParserEvent::UseSkill { name, .. } => {
                    assert_eq!(name, "fetch_quote");
                    count_use += 1;
                }
                ParserEvent::ParseError { reason, .. } => {
                    panic!("unexpected parse error: {}", reason);
                }
            }
        }
        assert_eq!(count_use, 1);
        assert_eq!(text, "Hi !");
    }

    #[test]
    fn t4_unclosed_tag_at_finalize_becomes_text() {
        let mut p = SkillCallParser::new();
        let evs = p.feed("hi <use_skill name=\"x\">{\"a\":1}");
        // not closed yet — no UseSkill
        for e in &evs {
            assert!(!matches!(e, ParserEvent::UseSkill { .. }));
        }
        let evs2 = p.finalize();
        // finalize should emit the unclosed content as text
        let mut got_text = String::new();
        for e in evs.into_iter().chain(evs2.into_iter()) {
            if let ParserEvent::TextDelta(s) = e {
                got_text.push_str(&s);
            }
        }
        assert!(got_text.contains("use_skill"));
    }

    #[test]
    fn t5_nested_use_skill_is_parse_error() {
        let mut p = SkillCallParser::new();
        let evs = p.feed(
            r#"<use_skill name="a">{"x": <use_skill name="b">{}</use_skill>}</use_skill>"#,
        );
        let mut saw_err = false;
        for e in evs {
            if let ParserEvent::ParseError { reason, .. } = e {
                assert!(reason.contains("nested"));
                saw_err = true;
            }
        }
        assert!(saw_err);
    }

    #[test]
    fn t6_invalid_json_inside_use_skill() {
        let mut p = SkillCallParser::new();
        let evs = p.feed(r#"<use_skill name="x">not json</use_skill>"#);
        let mut saw_err = false;
        for e in evs {
            if let ParserEvent::ParseError { reason, .. } = e {
                assert!(reason.contains("invalid JSON"));
                saw_err = true;
            }
        }
        assert!(saw_err);
    }

    #[test]
    fn t7_multiple_use_skills_emit_in_order() {
        let mut p = SkillCallParser::new();
        let evs = p.feed(
            r#"<use_skill name="a">{"i":1}</use_skill> mid <use_skill name="b">{"i":2}</use_skill>"#,
        );
        let names: Vec<String> = evs
            .into_iter()
            .filter_map(|e| match e {
                ParserEvent::UseSkill { name, input } => Some(format!("{}:{}", name, input["i"])),
                _ => None,
            })
            .collect();
        assert_eq!(names, vec!["a:1".to_string(), "b:2".to_string()]);
    }

    #[test]
    fn t8_utf8_boundary_handled_correctly() {
        let mut p = SkillCallParser::new();
        // a Chinese sentence wrapping a use_skill
        let evs = p.feed(r#"研究："茅台" <use_skill name="fetch_quote">{"tsCode":"600519.SH"}</use_skill> 完成"#);
        let mut saw_use = false;
        let mut text = String::new();
        for e in evs {
            match e {
                ParserEvent::UseSkill { name, .. } => {
                    assert_eq!(name, "fetch_quote");
                    saw_use = true;
                }
                ParserEvent::TextDelta(s) => text.push_str(&s),
                ParserEvent::ParseError { reason, .. } => panic!("unexpected: {}", reason),
            }
        }
        assert!(saw_use);
        assert!(text.contains("茅台"));
        assert!(text.contains("完成"));
    }

    #[test]
    fn t9_chunks_split_at_close_tag_boundary() {
        let mut p = SkillCallParser::new();
        let mut evs = vec![];
        evs.extend(p.feed(r#"<use_skill name="z">{"k":99}</use_sk"#));
        evs.extend(p.feed("ill> done"));
        let mut saw = false;
        let mut text = String::new();
        for e in evs {
            match e {
                ParserEvent::UseSkill { name, input } => {
                    assert_eq!(name, "z");
                    assert_eq!(input["k"], 99);
                    saw = true;
                }
                ParserEvent::TextDelta(s) => text.push_str(&s),
                _ => {}
            }
        }
        assert!(saw);
        assert_eq!(text, " done");
    }

    #[test]
    fn t10_malformed_opening_tag_errors() {
        let mut p = SkillCallParser::new();
        let evs = p.feed("<use_skill no-name>");
        let mut saw_err = false;
        for e in evs {
            if let ParserEvent::ParseError { .. } = e {
                saw_err = true;
            }
        }
        assert!(saw_err);
    }
}
