//! ToolCallParser — 在 chat stream 中扫描 `<use_tool>` 闭合。
//!
//! Spec: docs/design/agent-infra-module.md §2 Tool 调用文本协议，§5 ToolCallParser API
//!
//! 规则：
//! - Parser 实时增量扫描 provider stream；不缓冲整 turn。
//! - 检测到 `<use_tool name="X">` 后**只**缓冲到 `</use_tool>` 闭合，期间不 emit text_delta
//!   （避免泄漏 raw XML 给 UI）。
//! - 闭合后解析 JSON：成功 → emit `UseTool`；失败 → emit `ParseError`。
//! - 嵌套非法（`<use_tool>` 内部又出现 `<use_tool>`）→ `ParseError`。
//! - 流到 turn 结束（`finalize`）仍未闭合的 `<use_tool>` 当 text 处理（不 dispatch）。

use crate::domain::agent::JsonSummary;

/// Parser 事件输出。
#[derive(Debug, Clone, PartialEq)]
pub enum ParserEvent {
    /// 透传给 stream 的文本。
    TextDelta(String),
    /// 检测到一次完整 `<use_tool name="X">{...}</use_tool>`，可 dispatch。
    UseTool { name: String, input: JsonSummary },
    /// 标签格式 / JSON 解析错误 → caller 应包装为 `<tool_error code="parse_error">` 回给模型。
    ParseError { reason: String, partial: String },
}

/// Parser 状态机：
/// - `Idle`：在普通文本中；检测 `<use_tool` 起手时切到 InOpeningTag。
/// - `InOpeningTag`：累积 opening tag 内容（直到 `>`）。
/// - `InContent`：在 `<use_tool ...>` 和 `</use_tool>` 之间，累积 JSON。
#[derive(Debug, Clone, PartialEq)]
enum State {
    Idle,
    InOpeningTag,
    InContent,
}

const USE_TOOL_OPEN: &str = "<use_tool";
const USE_TOOL_CLOSE: &str = "</use_tool>";

/// ToolCallParser — 增量扫描 chat stream 检测 `<use_tool>` 标签。
pub struct ToolCallParser {
    state: State,
    /// 当前还没决定是文本还是 tag 的字节缓冲（处理 partial chunk）。
    pending: String,
    /// `InContent` 状态下累积的 inner content（不含闭合标签）。
    content_buf: String,
    /// `InOpeningTag` 状态下累积的 opening tag（含 `<use_tool` 前缀）。
    opening_buf: String,
    /// 当前正在解析的 tool name（opening tag 解析出来的）。
    current_name: Option<String>,
}

impl ToolCallParser {
    pub fn new() -> Self {
        Self {
            state: State::Idle,
            pending: String::new(),
            content_buf: String::new(),
            opening_buf: String::new(),
            current_name: None,
        }
    }

    /// Feed a chunk of provider stream text. Returns parser events generated by this chunk.
    pub fn feed(&mut self, chunk: &str) -> Vec<ParserEvent> {
        let mut events: Vec<ParserEvent> = Vec::new();
        self.pending.push_str(chunk);
        self.process(&mut events);
        events
    }

    /// End-of-stream. Flush any pending text. Unclosed tags are treated as plain text.
    pub fn finalize(&mut self) -> Vec<ParserEvent> {
        let mut events: Vec<ParserEvent> = Vec::new();
        // Flush incomplete tags as text per spec.
        match self.state {
            State::Idle => {
                if !self.pending.is_empty() {
                    let text = std::mem::take(&mut self.pending);
                    if !text.is_empty() {
                        events.push(ParserEvent::TextDelta(text));
                    }
                }
            }
            State::InOpeningTag => {
                // Unclosed opening tag → flush as text.
                let mut text = std::mem::take(&mut self.opening_buf);
                text.push_str(&std::mem::take(&mut self.pending));
                events.push(ParserEvent::TextDelta(text));
                self.state = State::Idle;
            }
            State::InContent => {
                // Unclosed: flush opening + content as text.
                let mut text = format!("<use_tool name=\"{}\">", self.current_name.clone().unwrap_or_default());
                text.push_str(&std::mem::take(&mut self.content_buf));
                text.push_str(&std::mem::take(&mut self.pending));
                events.push(ParserEvent::TextDelta(text));
                self.state = State::Idle;
                self.current_name = None;
            }
        }
        events
    }

    fn process(&mut self, events: &mut Vec<ParserEvent>) {
        // Loop until pending no longer changes shape.
        loop {
            let progressed = match self.state {
                State::Idle => self.step_idle(events),
                State::InOpeningTag => self.step_opening(events),
                State::InContent => self.step_content(events),
            };
            if !progressed {
                break;
            }
        }
    }

    /// In Idle state: emit text up to next `<use_tool` (if seen). If partial prefix of `<use_tool`
    /// at end of pending, hold off to wait for more input.
    fn step_idle(&mut self, events: &mut Vec<ParserEvent>) -> bool {
        if let Some(pos) = self.pending.find(USE_TOOL_OPEN) {
            // Emit everything before the tag start as text.
            let prefix: String = self.pending.drain(..pos).collect();
            if !prefix.is_empty() {
                events.push(ParserEvent::TextDelta(prefix));
            }
            // Move USE_TOOL_OPEN ("<use_tool") into opening_buf and advance.
            let head: String = self.pending.drain(..USE_TOOL_OPEN.len()).collect();
            self.opening_buf = head;
            self.state = State::InOpeningTag;
            return true;
        }
        // Tag not found. We may have a partial prefix of `<use_tool` at the end. Keep it pending
        // and flush the safe-text prefix.
        if let Some(safe_end) = safe_emit_idx(&self.pending, USE_TOOL_OPEN) {
            if safe_end > 0 {
                let prefix: String = self.pending.drain(..safe_end).collect();
                if !prefix.is_empty() {
                    events.push(ParserEvent::TextDelta(prefix));
                }
                return true;
            }
        }
        false
    }

    /// Accumulate opening tag bytes until `>` is found. Then parse `name="..."` and switch to
    /// InContent. Disallow nested `<use_tool` inside opening tag.
    fn step_opening(&mut self, events: &mut Vec<ParserEvent>) -> bool {
        // Move bytes from pending to opening_buf until `>` is found, with a safety cap.
        let mut found_gt = None;
        for (i, ch) in self.pending.char_indices() {
            if ch == '>' {
                found_gt = Some(i + ch.len_utf8());
                break;
            }
        }
        let Some(end) = found_gt else {
            // Move everything into opening_buf and wait for more.
            self.opening_buf.push_str(&self.pending);
            self.pending.clear();
            return false;
        };
        let head: String = self.pending.drain(..end).collect();
        self.opening_buf.push_str(&head);
        // self.opening_buf now contains `<use_tool ... >`
        match parse_opening_tag(&self.opening_buf) {
            Ok(name) => {
                self.current_name = Some(name);
                self.opening_buf.clear();
                self.content_buf.clear();
                self.state = State::InContent;
            }
            Err(reason) => {
                let partial = std::mem::take(&mut self.opening_buf);
                events.push(ParserEvent::ParseError { reason, partial });
                self.state = State::Idle;
                self.current_name = None;
            }
        }
        true
    }

    /// Accumulate JSON content until `</use_tool>` or detect nested `<use_tool` (illegal).
    fn step_content(&mut self, events: &mut Vec<ParserEvent>) -> bool {
        // Find the earlier of `</use_tool>` (close) or `<use_tool` (illegal nest).
        let pos_close = self.pending.find(USE_TOOL_CLOSE);
        let pos_nest = self.pending.find(USE_TOOL_OPEN);

        if let (Some(pn), Some(pc)) = (pos_nest, pos_close) {
            // If nest occurs before close: illegal.
            if pn < pc {
                let mut partial = self.content_buf.clone();
                partial.push_str(&self.pending[..=pn]);
                self.content_buf.clear();
                self.pending.clear();
                events.push(ParserEvent::ParseError {
                    reason: "nested <use_tool> not allowed".into(),
                    partial,
                });
                self.state = State::Idle;
                self.current_name = None;
                return true;
            }
        } else if let Some(pn) = pos_nest {
            // Only nest found (no close yet) → illegal.
            let mut partial = self.content_buf.clone();
            partial.push_str(&self.pending[..=pn]);
            self.content_buf.clear();
            self.pending.clear();
            events.push(ParserEvent::ParseError {
                reason: "nested <use_tool> not allowed".into(),
                partial,
            });
            self.state = State::Idle;
            self.current_name = None;
            return true;
        }

        if let Some(pc) = pos_close {
            // Move pending[..pc] into content_buf; consume close tag; parse JSON.
            let inner: String = self.pending.drain(..pc).collect();
            self.content_buf.push_str(&inner);
            // Drop the close tag.
            self.pending.drain(..USE_TOOL_CLOSE.len());
            // Parse JSON
            let raw_inner = std::mem::take(&mut self.content_buf);
            let trimmed = raw_inner.trim();
            let name = self.current_name.take().unwrap_or_default();
            // 容忍模型在合法 JSON 后追加垃圾（gpt-5 长输入常见 "trailing characters"，导致
            // run_subagent 这类长 prompt 反复 parse_error）：用流式 deserializer 取**第一个完整
            // JSON 对象**，忽略其后多余内容。仍对真正非法的 JSON 报 parse_error。
            //
            // 注意：StreamDeserializer 在首值后紧跟 `]` / `}` / `,` 时会在**第一个值**上就报
            // TrailingCharacters（实网抓到 gpt-5 输出 `{...}]`）——所以失败时再用括号平衡扫描
            // 取首个完整 {…}/[…] 前缀兜底；两条路都不行才算真 parse_error。
            let parse_result = parse_first_json_value(trimmed);
            match parse_result {
                Ok(input) => events.push(ParserEvent::UseTool { name, input }),
                Err(reason) => events.push(ParserEvent::ParseError {
                    reason: format!("invalid JSON in <use_tool>: {}", reason),
                    partial: raw_inner,
                }),
            }
            self.state = State::Idle;
            return true;
        }

        // Neither close nor nest found. Keep bytes in content_buf but hold a small tail to handle
        // partial `</use_tool>` or `<use_tool` straddling chunks.
        if let Some(safe_end) = safe_emit_idx(&self.pending, USE_TOOL_CLOSE) {
            let safe_end2 = match safe_emit_idx(&self.pending[..safe_end], USE_TOOL_OPEN) {
                Some(x) => x.min(safe_end),
                None => safe_end,
            };
            if safe_end2 > 0 {
                let chunk: String = self.pending.drain(..safe_end2).collect();
                self.content_buf.push_str(&chunk);
                return true;
            }
        }
        false
    }

}

impl Default for ToolCallParser {
    fn default() -> Self {
        Self::new()
    }
}

/// 取 `<use_tool>` body 里的第一个完整 JSON 值，容忍其后的尾部垃圾（spec §2 容错条款）。
///
/// 两级解析：① StreamDeserializer 首值（容忍空白分隔的尾巴）；② 失败时括号平衡扫描首个
/// `{…}` / `[…]` 前缀再 `from_str`（容忍 `{...}]` 这类 StreamDeserializer 直接报
/// TrailingCharacters 的粘连尾巴）。都失败 → 报首次错误。
fn parse_first_json_value(trimmed: &str) -> Result<JsonSummary, String> {
    if trimmed.is_empty() {
        return Err("empty <use_tool> body".to_string());
    }
    let mut stream = serde_json::Deserializer::from_str(trimmed).into_iter::<JsonSummary>();
    match stream.next() {
        Some(Ok(v)) => Ok(v),
        Some(Err(first_err)) => match balanced_json_prefix(trimmed) {
            Some(prefix) => {
                serde_json::from_str::<JsonSummary>(prefix).map_err(|_| first_err.to_string())
            }
            None => Err(first_err.to_string()),
        },
        None => Err("empty <use_tool> body".to_string()),
    }
}

/// 字符串感知的括号平衡扫描：返回以 `{` / `[` 开头的首个完整平衡前缀。
/// 引号内的括号 / 转义引号不计；非对象/数组开头或始终不平衡 → None。
fn balanced_json_prefix(s: &str) -> Option<&str> {
    let bytes = s.as_bytes();
    let open = *bytes.first()?;
    let close = match open {
        b'{' => b'}',
        b'[' => b']',
        _ => return None,
    };
    let mut depth = 0usize;
    let mut in_str = false;
    let mut escape = false;
    for (i, &b) in bytes.iter().enumerate() {
        if in_str {
            if escape {
                escape = false;
            } else if b == b'\\' {
                escape = true;
            } else if b == b'"' {
                in_str = false;
            }
        } else if b == b'"' {
            in_str = true;
        } else if b == open {
            depth += 1;
        } else if b == close {
            depth = depth.checked_sub(1)?;
            if depth == 0 {
                return Some(&s[..=i]);
            }
        }
    }
    None
}

/// Compute the largest prefix length we can safely emit as text without risk of having started a tag.
/// Specifically, if the tail of `s` matches a prefix of `marker`, hold those bytes back.
fn safe_emit_idx(s: &str, marker: &str) -> Option<usize> {
    if s.is_empty() {
        return Some(0);
    }
    // Largest k <= s.len() such that s.ends_with(marker[..k]). Then safe_emit = s.len() - k.
    let max_k = s.len().min(marker.len());
    for k in (1..=max_k).rev() {
        if s.is_char_boundary(s.len() - k) {
            let tail = &s[s.len() - k..];
            if let Some(prefix) = marker.get(..k) {
                if tail == prefix {
                    return Some(s.len() - k);
                }
            }
        }
    }
    Some(s.len())
}

/// Parse `<use_tool name="X">` opening tag. Returns the name on success.
fn parse_opening_tag(tag: &str) -> Result<String, String> {
    // Expected shape: `<use_tool name="<name>">` (allow whitespace).
    let tag = tag.trim();
    let stripped = tag
        .strip_prefix(USE_TOOL_OPEN)
        .and_then(|s| s.strip_suffix('>'))
        .ok_or_else(|| "malformed opening tag".to_string())?;
    let stripped = stripped.trim();
    // Find `name=`
    let after_name = stripped
        .strip_prefix("name")
        .ok_or_else(|| "missing name= attribute".to_string())?
        .trim_start();
    let after_eq = after_name
        .strip_prefix('=')
        .ok_or_else(|| "missing = in name attribute".to_string())?
        .trim_start();
    // Quoted value.
    let quote = after_eq
        .chars()
        .next()
        .ok_or_else(|| "missing quoted name value".to_string())?;
    if quote != '"' && quote != '\'' {
        return Err("name attribute must be quoted".into());
    }
    let rest = &after_eq[quote.len_utf8()..];
    let close = rest
        .find(quote)
        .ok_or_else(|| "unterminated quoted name value".to_string())?;
    let name = &rest[..close];
    if name.is_empty() {
        return Err("empty tool name".into());
    }
    Ok(name.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn drain(p: &mut ToolCallParser, chunk: &str) -> Vec<ParserEvent> {
        p.feed(chunk)
    }

    #[test]
    fn t1_plain_text_emits_text_delta() {
        let mut p = ToolCallParser::new();
        let evs = drain(&mut p, "hello world");
        assert_eq!(evs, vec![ParserEvent::TextDelta("hello world".into())]);
    }

    #[test]
    fn t2_single_use_tool_complete_in_one_chunk() {
        let mut p = ToolCallParser::new();
        let evs = drain(
            &mut p,
            r#"before <use_tool name="fetch_quote">{"tsCode":"600519.SH"}</use_tool> after"#,
        );
        // expect: TextDelta("before "), UseTool, TextDelta(" after")
        let mut iter = evs.into_iter();
        match iter.next().unwrap() {
            ParserEvent::TextDelta(s) => assert_eq!(s, "before "),
            x => panic!("unexpected {:?}", x),
        }
        match iter.next().unwrap() {
            ParserEvent::UseTool { name, input } => {
                assert_eq!(name, "fetch_quote");
                assert_eq!(input["tsCode"], "600519.SH");
            }
            x => panic!("unexpected {:?}", x),
        }
        match iter.next().unwrap() {
            ParserEvent::TextDelta(s) => assert_eq!(s, " after"),
            x => panic!("unexpected {:?}", x),
        }
    }

    #[test]
    fn t3_chunk_split_in_middle_of_opening_tag() {
        let mut p = ToolCallParser::new();
        let mut evs = vec![];
        evs.extend(p.feed("Hi <use_to"));
        evs.extend(p.feed("ol name=\"fetch_quote\">{\"a\":1}</use_tool>!"));
        // collect texts and usetool counts
        let mut text = String::new();
        let mut count_use = 0;
        for e in evs {
            match e {
                ParserEvent::TextDelta(s) => text.push_str(&s),
                ParserEvent::UseTool { name, .. } => {
                    assert_eq!(name, "fetch_quote");
                    count_use += 1;
                }
                ParserEvent::ParseError { reason, .. } => {
                    panic!("unexpected parse error: {}", reason);
                }
            }
        }
        assert_eq!(count_use, 1);
        assert_eq!(text, "Hi !");
    }

    #[test]
    fn t4_unclosed_tag_at_finalize_becomes_text() {
        let mut p = ToolCallParser::new();
        let evs = p.feed("hi <use_tool name=\"x\">{\"a\":1}");
        // not closed yet — no UseTool
        for e in &evs {
            assert!(!matches!(e, ParserEvent::UseTool { .. }));
        }
        let evs2 = p.finalize();
        // finalize should emit the unclosed content as text
        let mut got_text = String::new();
        for e in evs.into_iter().chain(evs2.into_iter()) {
            if let ParserEvent::TextDelta(s) = e {
                got_text.push_str(&s);
            }
        }
        assert!(got_text.contains("use_tool"));
    }

    #[test]
    fn t5_nested_use_tool_is_parse_error() {
        let mut p = ToolCallParser::new();
        let evs = p.feed(
            r#"<use_tool name="a">{"x": <use_tool name="b">{}</use_tool>}</use_tool>"#,
        );
        let mut saw_err = false;
        for e in evs {
            if let ParserEvent::ParseError { reason, .. } = e {
                assert!(reason.contains("nested"));
                saw_err = true;
            }
        }
        assert!(saw_err);
    }

    #[test]
    fn t6_invalid_json_inside_use_tool() {
        let mut p = ToolCallParser::new();
        let evs = p.feed(r#"<use_tool name="x">not json</use_tool>"#);
        let mut saw_err = false;
        for e in evs {
            if let ParserEvent::ParseError { reason, .. } = e {
                assert!(reason.contains("invalid JSON"));
                saw_err = true;
            }
        }
        assert!(saw_err);
    }

    // 容忍合法 JSON 后的尾部垃圾（gpt-5 长输入常见）：取第一个完整对象，不再 parse_error。
    #[test]
    fn t6b_trailing_chars_after_valid_json_tolerated() {
        let mut p = ToolCallParser::new();
        let evs = p.feed(r#"<use_tool name="run_subagent">{"prompt":"hi"} 多余的尾巴}}</use_tool>"#);
        let mut got = None;
        for e in evs {
            match e {
                ParserEvent::UseTool { name, input } => got = Some((name, input)),
                ParserEvent::ParseError { .. } => panic!("尾部垃圾不应再 parse_error"),
                _ => {}
            }
        }
        let (name, input) = got.expect("应解析出 UseTool");
        assert_eq!(name, "run_subagent");
        assert_eq!(input["prompt"], "hi");
    }

    #[test]
    fn t7_multiple_use_tools_emit_in_order() {
        let mut p = ToolCallParser::new();
        let evs = p.feed(
            r#"<use_tool name="a">{"i":1}</use_tool> mid <use_tool name="b">{"i":2}</use_tool>"#,
        );
        let names: Vec<String> = evs
            .into_iter()
            .filter_map(|e| match e {
                ParserEvent::UseTool { name, input } => Some(format!("{}:{}", name, input["i"])),
                _ => None,
            })
            .collect();
        assert_eq!(names, vec!["a:1".to_string(), "b:2".to_string()]);
    }

    #[test]
    fn t8_utf8_boundary_handled_correctly() {
        let mut p = ToolCallParser::new();
        // a Chinese sentence wrapping a use_tool
        let evs = p.feed(r#"研究："茅台" <use_tool name="fetch_quote">{"tsCode":"600519.SH"}</use_tool> 完成"#);
        let mut saw_use = false;
        let mut text = String::new();
        for e in evs {
            match e {
                ParserEvent::UseTool { name, .. } => {
                    assert_eq!(name, "fetch_quote");
                    saw_use = true;
                }
                ParserEvent::TextDelta(s) => text.push_str(&s),
                ParserEvent::ParseError { reason, .. } => panic!("unexpected: {}", reason),
            }
        }
        assert!(saw_use);
        assert!(text.contains("茅台"));
        assert!(text.contains("完成"));
    }

    #[test]
    fn t9_chunks_split_at_close_tag_boundary() {
        let mut p = ToolCallParser::new();
        let mut evs = vec![];
        evs.extend(p.feed(r#"<use_tool name="z">{"k":99}</use_to"#));
        evs.extend(p.feed("ol> done"));
        let mut saw = false;
        let mut text = String::new();
        for e in evs {
            match e {
                ParserEvent::UseTool { name, input } => {
                    assert_eq!(name, "z");
                    assert_eq!(input["k"], 99);
                    saw = true;
                }
                ParserEvent::TextDelta(s) => text.push_str(&s),
                _ => {}
            }
        }
        assert!(saw);
        assert_eq!(text, " done");
    }

    #[test]
    fn t10_malformed_opening_tag_errors() {
        let mut p = ToolCallParser::new();
        let evs = p.feed("<use_tool no-name>");
        let mut saw_err = false;
        for e in evs {
            if let ParserEvent::ParseError { .. } = e {
                saw_err = true;
            }
        }
        assert!(saw_err);
    }

    #[test]
    fn t6c_glued_bracket_tail_after_valid_json_tolerated() {
        // 实网回归（2026-06-10，gpt-5.4 输出 run_subagent）：合法对象后**紧贴**一个 `]`——
        // StreamDeserializer 对 `,]}` 开头的尾巴在首值上就报 TrailingCharacters，
        // 必须走括号平衡兜底。垃圾尾巴还包括重复 `}`、粘连文字等。
        for tail in ["]", "}", "]]", "} ]", "garbage"] {
            let mut p = ToolCallParser::new();
            let body = format!(
                r#"<use_tool name="run_subagent">{{"prompt":"调研","allowedTools":["web_search"]}}{tail}</use_tool>"#
            );
            let mut evs = p.feed(&body);
            evs.extend(p.finalize());
            let tool = evs.iter().find_map(|e| match e {
                ParserEvent::UseTool { name, input } => Some((name.clone(), input.clone())),
                _ => None,
            });
            let (name, input) = tool.unwrap_or_else(|| panic!("tail={tail:?} 应解析出 UseTool，evs={evs:?}"));
            assert_eq!(name, "run_subagent");
            assert_eq!(input["prompt"], "调研");
            assert_eq!(input["allowedTools"][0], "web_search");
        }
    }

    #[test]
    fn balanced_json_prefix_respects_strings_and_escapes() {
        assert_eq!(
            balanced_json_prefix(r#"{"a":"}"}]junk"#),
            Some(r#"{"a":"}"}"#)
        );
        assert_eq!(
            balanced_json_prefix(r#"{"a":"\"}"}x"#),
            Some(r#"{"a":"\"}"}"#)
        );
        assert_eq!(balanced_json_prefix(r#"[{"a":1}]]"#), Some(r#"[{"a":1}]"#));
        assert_eq!(balanced_json_prefix("not json"), None);
        assert_eq!(balanced_json_prefix(r#"{"never closed"#), None);
    }
}
