
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<Result<PingResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExternal(url: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_external", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 同步读取 News 本地读模型。
 * 
 * Spec: news-module.md §4 fetch_news
 */
async fetchNews(request: FetchNewsRequest) : Promise<Result<FetchNewsResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_news", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出当前已知 source。
 * 
 * Spec: news-module.md §4 list_news_sources
 */
async listNewsSources() : Promise<Result<ListNewsSourcesResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_news_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 显式 warm articles。
 * 
 * Spec: news-module.md §5 warm_articles
 */
async warmArticles(request: WarmArticlesRequest) : Promise<Result<WarmArticlesResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warm_articles", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMarket(request: ListMarketRequest) : Promise<Result<ListMarketResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_market", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchData(request: FetchDataRequest) : Promise<Result<FetchDataResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_data", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanMarket(request: ScanMarketRequest) : Promise<Result<ScanMarketResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_market", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 市场宽度（spec §4 `market_breadth`）。
 * 
 * 纯只读聚合，不触发 provider；只统计 `category == stock`。
 */
async fetchMarketBreadth() : Promise<Result<MarketBreadth, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_market_breadth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 行业热度（spec §4 `industry_heatmap`）。
 * 
 * `top_n` 缺省时使用 5；上限 50（防止 UI 误传大值）。
 */
async fetchIndustryHeatmap(topN: number | null) : Promise<Result<IndustryHeatmap, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_industry_heatmap", { topN }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端 on-demand 拉数据：用户选中标的 + 切到某 chart period 时，如果 DB 空就触发后端拉一份。
 * 
 * 按 period 字符串分派：
 * - `"day"` / `"week"` / `"month"` → `refresh_klines`
 * - `"1m"` / `"5m"` / `"15m"` / `"30m"` / `"60m"` → `refresh_minute_klines`
 * - `"intraday"` → `refresh_intraday`
 * 
 * 同步等待 refresh 完成；调用方拿到 Ok 后可以再次调用 fetch_data 拿数据。
 * 
 * 已有数据时也会重新拉（refresh 是 upsert，幂等）；UI 调用方决定是否要重新触发。
 */
async ensureChartData(tsCode: string, period: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_chart_data", { tsCode, period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端左拉到尽头时触发：扩展该 ts_code 的历史 K 线深度到 `target_days`。
 * 
 * - `target_days <= TDX_SINGLE_FETCH_LIMIT (800)`：走 TDX 主路径（最多 ~3 年）
 * - `target_days > 800` 且 TushareHealthState.isAvailable：走 TuShare 长历史扩展段
 * - 否则 silent skip 长历史
 * 
 * `period` 字符串："day" / "week" / "month"。分钟 K 不走此命令（TDX 限 800 根，分钟 K 一天就 240 根）。
 * 
 * Spec: docs/design/quotes-module.md §4 + §5 K 线长历史
 */
async extendChartHistory(tsCode: string, period: string, targetDays: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extend_chart_history", { tsCode, period, targetDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 拉一页 K 线（渐进式加载用）。`start_offset` 为从最新往回跳过的根数：
 * - 0 = 最新一批
 * - 800 = 再往前一批
 * - ...
 * 
 * 后端 upsert 写 DB 后返回 `(addedCount, hasMore)`。前端先拉 start=0 显示首屏，
 * 再 background loop 800/1600/... applyMoreData，直到 hasMore=false 停。
 * 
 * 仅支持 day/week/month；分钟 K 不需要分页（一次 800 根足够）。
 */
async fetchKlinePage(tsCode: string, period: string, startOffset: number) : Promise<Result<KlinePageResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_kline_page", { tsCode, period, startOffset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 聚焦按需刷新一批 quotes（spec §5「实时行情（聚焦按需）」）：前端把当前关注的标的
 * （自选 / 可见列表 / 详情）传入，后端按新鲜度跳过 + 80/批并发跑连接池刷 `MARKET_SNAPSHOT`，
 * 通过 `market-quotes-refresh-progress`(scope=subscribed) 增量推回前端。非法 ts_code 跳过。
 */
async refreshQuotes(tsCodes: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_quotes", { tsCodes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 并行探测全部 TDX 行情站点延时（给前端「延时 popup」）。
 * 
 * 返回每台 `{ name, host, port, latencyMs, ok, inPool }`，按「可达 + 延迟」排序；
 * `inPool` = 该台是否在当前 active 连接池（低延时子集）里。探测阻塞 → spawn_blocking。
 * 
 * Spec: docs/design/quotes-module.md §TDX 连接池与并发。
 */
async probeTdxHosts() : Promise<Result<HostProbe[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_tdx_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Frontend log forwarder：前端调 commands.forwardLog(msg) → 后端 tracing
 * → tauri dev stdout，可以从开发者那里直接读 log 文件分析性能问题。
 * 仅供 dev / 调试用，生产 build 可去掉。
 */
async forwardLog(level: string, message: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forward_log", { level, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出当前 ToolRegistry 已注册的 tool。
 * 
 * Spec: agent-infra-module.md §5 Tool Registry API（snapshot）
 */
async agentListTools() : Promise<Result<ToolSpec[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_tools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 返回内置快速预设（DeepSeek / OpenAI / Anthropic 官方）。
 * 
 * Spec §5 前端命令：`agent_channel_presets`
 */
async agentChannelPresets() : Promise<Result<ChannelPresetView[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_channel_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 调对应 wireFormat 的 `/models` 接口发现可用模型。
 * 
 * Spec §5 模型发现 API：发现失败时调用方引导用户手填模型名。
 */
async agentDiscoverModels(wireFormat: WireFormat, baseUrl: string, apiKey: string) : Promise<Result<DiscoveredModel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_discover_models", { wireFormat, baseUrl, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 用已有渠道的存储凭据发现模型（API key 不回显，复用服务端存储的 key）。
 */
async agentDiscoverModelsForChannel(channelId: string) : Promise<Result<DiscoveredModel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_discover_models_for_channel", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 添加一条渠道。生成 channelId（`ch_<uuid>`），stream=true，能力缺省 false。
 * 若是首条渠道，自动设为 active。
 * 
 * Spec §2：每个确认保留的模型各成一条 ProviderChannel；维护 active 渠道。
 */
async agentAddChannel(input: AddChannelInput) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_add_channel", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 编辑已有渠道（按 channelId）。apiKey 为空/省略保留原 key；不改 is_active；
 * 未暴露字段保留原值。channelId 不存在 → not_found。
 * 
 * Spec §5 前端命令：`agent_update_channel`
 */
async agentUpdateChannel(input: UpdateChannelInput) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_update_channel", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出所有渠道（**屏蔽 apiKey 明文**）。
 * 
 * Spec §5 前端命令：`agent_list_channels`（屏蔽 apiKey）
 */
async agentListChannels() : Promise<Result<ProviderChannelView[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_channels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除一条渠道。
 */
async agentRemoveChannel(channelId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_remove_channel", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置当前 active 渠道。
 * 
 * Spec §5 前端命令：`agent_set_active_channel`
 */
async agentSetActiveChannel(channelId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_set_active_channel", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取当前 active 渠道（屏蔽 apiKey）。
 */
async agentGetActiveChannel() : Promise<Result<ProviderChannelView | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_get_active_channel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchAccount(request: FetchAccountRequest) : Promise<Result<FetchAccountResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_account", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWatchlist(request: UpdateWatchlistRequest) : Promise<Result<UpdateWatchlistResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_watchlist", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markTriggerHandled(request: MarkTriggerHandledRequest) : Promise<Result<MarkTriggerHandledResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_trigger_handled", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildAccountSnapshot() : Promise<Result<AccountSnapshot, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_account_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重置账户 = 重开一局模拟盘（用户主动操作，前端带确认弹窗）。
 * Spec: account-module.md §4 `account_reset`。
 */
async accountReset() : Promise<Result<AccountResetResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("account_reset") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出历史归档局摘要（复盘取回）。
 * Spec: account-module.md §4 `list_account_archives`。
 */
async listAccountArchives() : Promise<Result<ListAccountArchivesResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_account_archives") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 提交一条用户消息，跑一次 dialogue run（同步等到终态；流式经 `agent-event`）。
 */
async agentSendMessage(input: SendMessageInput) : Promise<Result<SendMessageResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_send_message", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Agent 总览快照（按 `include` 选择器返回各段；未选的省略）。
 * 
 * 未传 `include` → 默认返回 strategy + runs + analysisResults（向后兼容）。
 */
async agentFetchState(input: FetchStateInput | null) : Promise<Result<AgentStateSnapshot, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_fetch_state", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 当前 active 投资策略（+ 可选历史版本，+ status 过滤）。
 */
async agentFetchStrategy(input: FetchStrategyInput | null) : Promise<Result<FetchStrategyResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_fetch_strategy", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 写一个策略新版本（用户在对话中确认后调；版本化 + 乐观并发）。
 */
async agentUpsertStrategy(input: UpsertStrategyInput) : Promise<Result<UpsertStrategyResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_upsert_strategy", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动触发一次收盘复盘（只读 review run → 落盘 markdown 报告）。流式经 `agent-event`。
 */
async agentRunReview(input: RunReviewInput) : Promise<Result<RunReviewResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_run_review", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出已落盘的复盘报告（最新在前）。`limit` 截断返回条数（spec §9 `ListReviewReportsRequest`）。
 */
async agentListReviewReports(limit: number | null) : Promise<Result<ReviewReportRef[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_review_reports", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出所有用户会话（按最近活跃排序，过滤子 agent 会话）。
 */
async agentListConversations() : Promise<Result<ConversationSummary[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_conversations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 加载指定对话的全部持久化消息（按 seq 排序；审计真源）。
 * 
 * 加载对话消息（从最近 summary 检查点开始，不加载更早的历史）。
 * Spec: agent-infra-module.md §5 `load_conversation_view`
 */
async agentLoadConversation(conversationId: string) : Promise<Result<AgentMessage[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_load_conversation", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 加载指定 run 的全部 ToolCall（按 started_at 升序）。
 * 
 * Spec: agent-infra-module.md §5
 */
async agentLoadToolCalls(runId: string) : Promise<Result<ToolCall[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_load_tool_calls", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取复盘报告文件内容（Markdown）。
 */
async agentReadReviewReport(path: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_read_review_report", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消一个在跑的 run（dialogue/news/review 等）。
 */
async agentCancelRun(input: CancelRunInput) : Promise<Result<CancelRunResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_cancel_run", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读 news 自动分析开关当前状态（spec §5：默认关闭）。
 */
async agentGetNewsAutoAnalysis() : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_get_news_auto_analysis") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 开/关 news 自动分析（spec §5）。开启（false→true）时回填最近 `news_buffer_window_secs`
 * 内的 news 入 buffer。返回新状态 + 回填条数。
 */
async agentSetNewsAutoAnalysis(enabled: boolean) : Promise<Result<SetNewsAutoAnalysisResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_set_news_auto_analysis", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 单局归档摘要（复盘取回）。
 */
export type AccountArchive = { season: number; resetAt: string; initialCash: Money; finalCash: Money; finalEquity: Money; realizedPnl: Money; fillCount: number; closedPositionCount: number; eventCount: number }
/**
 * Spec: account-module.md §2 AccountEvent。
 */
export type AccountEvent = { eventId: string; eventType: AccountEventType; orderId?: string | null; fillId?: string | null; positionId?: string | null; tsCode?: TsCode | null; reason?: string | null; 
/**
 * `agent` | `system` | `user`（AccountActor）。
 */
actor: string; payload: JsonValue; occurredAt: string }
/**
 * Spec: account-module.md §2 AccountEventType。
 */
export type AccountEventType = "account_initialized" | "order_placed" | "order_cancelled" | "order_rejected" | "order_expired" | "order_partially_filled" | "order_filled" | "position_opened" | "position_scaled" | "position_closed" | "protection_adjusted" | "watchlist_added" | "watchlist_removed" | "watchlist_note_updated" | "cash_frozen" | "cash_released" | "shares_frozen" | "shares_released" | "invalidation_signal_recorded" | "trigger_created" | "trigger_handled" | "snapshot_rebuilt"
/**
 * 重置账户响应：新局序号 + 新局空局快照。
 */
export type AccountResetResponse = { season: number; snapshot: AccountSnapshot }
/**
 * 指向 Account 返回的稳定 ID（spec §3 `AccountResultRef`）。
 * 
 * Account 不知 `tradeId/runId/strategyVersion`；只回这些自有 ID。
 */
export type AccountResultRef = { accepted: boolean; orderId?: string | null; fillIds: string[]; positionId?: string | null; accountEventIds: string[]; rejectionEventId?: string | null; reason?: ErrorCode | null; message?: string | null }
/**
 * Spec: account-module.md §2 账户快照
 */
export type AccountSnapshot = { initialCash: Money; cash: Money; availableCash: Money; frozenCash: Money; marketValue: Money; totalAssets: Money; realizedPnl: Money; unrealizedPnl: Money; totalPnl: Money; pricedPositionCount: number; unpricedPositionCount: number; valuationFreshness: Freshness; openPositionCount: number; pendingOrderCount: number; capturedAt: string; warnings?: WarningCode[] }
/**
 * Spec: account-module.md §2 AccountTrigger。
 */
export type AccountTrigger = { triggerId: string; triggerType: AccountTriggerType; orderId?: string | null; positionId?: string | null; tsCode?: TsCode | null; price?: Price | null; 
/**
 * 触发阈值（字符串编码），可表示 Price / OccurredAt / signal label。
 */
threshold?: string | null; quoteFreshness?: Freshness | null; warnings?: WarningCode[]; eventId: string; handled: boolean; occurredAt: string }
export type AccountTriggerType = "stop_loss" | "take_profit" | "time_stop" | "order_filled" | "order_rejected" | "order_expired" | "invalidated"
/**
 * 添加渠道的请求 —— 一条确认保留的模型成一条渠道。
 */
export type AddChannelInput = { 
/**
 * 用户输入的渠道名（展示用 provider name）。
 */
provider: string; wireFormat: WireFormat; baseUrl?: string | null; apiKey: string; model: string; 
/**
 * 可选能力标记；缺省 false。
 */
supportsVision?: boolean | null; supportsThinking?: boolean | null; maxOutputTokens?: number | null; contextWindowTokens?: number | null }
export type Adjust = "none" | "qfq" | "hfq"
/**
 * 一条 Agent 消息（context / 持久化对话历史）。
 * 
 * Spec: agent-infra-module.md §2 `AgentMessage`
 */
export type AgentMessage = { messageId: string; runId?: string | null; 
/**
 * 多轮会话标识（Runtime 提供）；跨 run 续接靠它分组（spec §2）。
 */
conversationId?: string | null; 
/**
 * 会话内单调序号；持久化排序用（spec §2）。
 */
seq?: number | null; 
/**
 * 消息种类：默认 chat；summary = 压缩检查点（durable，不再被压缩）（spec §2）。
 */
kind?: MessageKind | null; role: AgentMessageRole; blocks: AgentMessageBlock[]; createdAt: string }
/**
 * AgentMessage block 类型。
 * 
 * Spec: agent-infra-module.md §2 `AgentMessageBlock`
 * 
 * Tool 调用 / 结果（`<use_tool>` / `<tool_result>` / `<tool_error>`）嵌在 text block 中。
 */
export type AgentMessageBlock = { type: "text"; text: string } | { type: "image"; mimeType: string; dataRef: string } | { type: "thinking"; text: string; provider?: string | null; metadata?: JsonValue | null }
/**
 * AgentMessage 角色枚举。
 * 
 * Spec: agent-infra-module.md §2
 * 
 * 注：`tool` role 不存在；tool_result 以 `user` role + text block（含 `<tool_result>` XML）形式回写。
 */
export type AgentMessageRole = "system" | "user" | "assistant"
/**
 * 一次 Agent run —— 决策链主键。
 * 
 * Spec: agent-runtime-module.md §3 `AgentRun`
 * 
 * 规则：
 * - `run_id` 是事件 / 工具调用 / 模型 turn / AnalysisResult / AgentTrade 的关联键。
 * - **策略版本冻结**：run 创建时把 active `version` 写入 `strategy_version`，全程不变。
 * - `review` run 可由收盘调度起（顶层，`trigger=eod_review`），也可被对话/news fork
 * （`parent_run_id` 指向父 run）；两种都只读、不下单。
 */
export type AgentRun = { runId: string; mode: AgentRunMode; trigger: AgentRunTrigger; 
/**
 * review 被对话/news fork 时指向父 run。
 */
parentRunId?: string | null; provider: string; wireFormat: WireFormat; model: string; 
/**
 * run 创建时冻结的 active 策略版本（无策略时缺省）。
 */
strategyVersion?: number | null; 
/**
 * account_trigger run 经 `orderId → runId` 反查关联到原始建仓 run。
 */
causationRunId?: string | null; status: AgentRunStatus; startedAt?: string | null; endedAt?: string | null; error?: string | null }
/**
 * 四种运行模式（spec §3 mode 表）。trigger 与 mode 一一对应。
 */
export type AgentRunMode = 
/**
 * 用户消息驱动的连续对话线程。
 */
"dialogue" | 
/**
 * news buffer M/N 触发的隔离单次分析。
 */
"news" | 
/**
 * `account-triggered` 实时唤起（止损/成交等）。
 */
"account_trigger" | 
/**
 * 收盘调度 / 被对话·news fork 的只读复盘（永不下单）。
 */
"review"
/**
 * run 生命周期状态。
 */
export type AgentRunStatus = "queued" | "running" | "completed" | "failed" | "cancelled"
/**
 * run 的触发来源（spec §3 `AgentRunTrigger`）。
 */
export type AgentRunTrigger = { kind: "user_chat"; message_id: string } | { kind: "news_batch"; news_ids: string[] } | { kind: "account_trigger"; trigger_id: string } | { kind: "eod_review"; trade_date: string }
/**
 * Agent 总览快照（spec §9 fetch_agent_state）。
 */
export type AgentStateSnapshot = { activeStrategy?: InvestmentStrategy | null; recentRuns: AgentRun[]; recentResults: AnalysisResult[]; recentTrades: AgentTrade[]; recentMessages: AgentMessage[]; recentToolCalls: ToolCall[] }
/**
 * 每次 `operate_account` 的审计戳 —— runtime 侧、不耦合 Account。
 * 
 * Spec: agent-runtime-module.md §3 `AgentTrade`
 * 
 * 崩溃恢复：调 Account 前先落 `submitting`，返回后填 `account_result_ref` 转 `settled`；
 * 启动恢复用 `client_order_id` 反查对账（Account 侧去重为延后加固项）。
 */
export type AgentTrade = { tradeId: string; runId: string; 
/**
 * 幂等键：下单前生成，传给 Account 去重 + 恢复对账。
 */
clientOrderId: string; 
/**
 * 来自 `AgentRun.strategy_version`（冻结值）。
 */
strategyVersion?: number | null; reason: string; 
/**
 * `OperateAccountInput` 的可读摘要（不重定义账户命令）。
 */
accountInputSummary: string; status: AgentTradeStatus; accountResultRef?: AccountResultRef | null; createdAt: string; updatedAt: string }
/**
 * AgentTrade 两态（spec §3）：`submitting`=调用前已落库；`settled`=拿到 Account 结果。
 */
export type AgentTradeStatus = "submitting" | "settled"
/**
 * 成交额，CNY。
 */
export type Amount = string
/**
 * news 分析产物 —— 前端右侧列表。
 * 
 * Spec: agent-runtime-module.md §3 `AnalysisResult`
 * 
 * `no_action` 也要 emit；证据按 `run_id` 拉 `fetch_news` ToolCall，不另存快照。
 */
export type AnalysisResult = { resultId: string; runId: string; kind: AnalysisResultKind; 
/**
 * 结论 + 理由（含「为什么现在进还来得及 / 已 price-in」判断）。
 */
summary: string; relatedCodes: TsCode[]; 
/**
 * 若 kind=action 且下单，关联 AgentTrade。
 */
tradeIds: string[]; createdAt: string }
export type AnalysisResultKind = 
/**
 * 触发了动作（下单 / 改自选）。
 */
"action" | 
/**
 * 明确不行动（大多数 news 应是此）。
 */
"no_action"
export type ArticleSnippet = { title?: string | null; content: string; fetchedAt?: string | null }
/**
 * spec §9 `CancelAgentRunRequest = { runId; reason? }`。
 */
export type CancelRunInput = { runId: string; 
/**
 * 取消理由（审计）。
 */
reason?: string | null }
/**
 * spec §9 `CancelAgentRunResponse = { accepted; runId; status }`。
 */
export type CancelRunResult = { accepted: boolean; runId: string; status: CancelRunStatusDto }
/**
 * spec §9 `CancelAgentRunResponse.status`。
 */
export type CancelRunStatusDto = "cancelled" | "completed" | "failed" | "not_found"
/**
 * 快速预设视图（返回给设置页）。
 */
export type ChannelPresetView = { key: string; provider: string; wireFormat: WireFormat; baseUrl: string }
export type CommandError = { code: ErrorCode; message?: string | null; details?: JsonValue | null }
/**
 * Spec: quotes-module.md §2 CompanyEvent
 */
export type CompanyEvent = { id: string; tsCode: TsCode; eventType: CompanyEventType; announceDate?: string | null; effectiveDate?: string | null; payload: JsonValue; source: string; fetchedAt: string }
export type CompanyEventType = "dividend" | "suspension" | "resume" | "st" | "earnings_forecast" | "unlock" | "other"
/**
 * 对话列表条目（前端 sidebar 用）。
 */
export type ConversationSummary = { conversationId: string; messageCount: number; firstAt: string; lastAt: string; preview: string }
/**
 * Spec: quotes-module.md §2 基本面读模型
 */
export type DailyBasic = { tsCode: TsCode; tradeDate: string; pe?: number | null; peTtm?: number | null; pb?: number | null; ps?: number | null; psTtm?: number | null; turnoverRate?: number | null; turnoverRateFloat?: number | null; volumeRatio?: number | null; totalMv?: Money | null; circMv?: Money | null; source: string; fetchedAt: string }
/**
 * 发现到的单个可用模型。
 */
export type DiscoveredModel = { id: string; displayName?: string | null }
export type ErrorCode = "invalid_input" | "not_found" | "provider_unavailable" | "rate_limited" | "db_error" | "parse_error" | "quote_missing" | "quote_stale" | "quote_price_missing" | "depth_missing" | "outside_trading_session" | "instrument_not_tradable" | "instrument_suspended" | "limit_up_down_blocked" | "insufficient_cash" | "insufficient_sellable_quantity" | "invalid_lot_size" | "order_not_pending" | "risk_limit_exceeded" | "strategy_required" | "duplicate_event" | "version_conflict" | "article_extract_failed" | "tool_timeout" | "provider_context_too_long" | 
/**
 * 本地写 tool（write_file / edit_file）的 path 规范化后越界 <workspace>。
 * Spec: agent-runtime-module.md §4.2 本地通用 tool 契约（建议 A）。
 */
"path_outside_workspace" | 
/**
 * run_bash 命中危险命令门禁被拒（约定级，非强隔离）。
 * Spec: agent-runtime-module.md §2 run_bash 危险命令门禁 / §4.2。
 */
"command_rejected"
export type FetchAccountInclude = { snapshot?: boolean | null; positions?: boolean | null; orders?: boolean | null; watchlist?: boolean | null; events?: boolean | null; triggers?: boolean | null }
export type FetchAccountRequest = { include?: FetchAccountInclude | null; positionStatus?: PositionStatusFilter | null; orderActive?: boolean | null; orderStatusIn?: OrderStatus[] | null; triggerHandled?: TriggerHandledFilter | null; limit?: number | null; offset?: number | null }
export type FetchAccountResponse = { snapshot?: AccountSnapshot | null; positions?: Position[] | null; orders?: Order[] | null; watchlist?: WatchlistItemView[] | null; events?: AccountEvent[] | null; triggers?: AccountTrigger[] | null; warnings?: WarningCode[] }
export type FetchDataItem = { tsCode: TsCode; category: InstrumentCategory; name?: string | null; quote?: StockQuote | null; quoteFreshness?: Freshness | null; intraday?: IntradaySeries | null; klines?: Partial<{ [key in string]: KlineSeries }> | null; minuteKlines?: Partial<{ [key in string]: MinuteKlineSeries }> | null; indicators?: IndicatorSnapshot | null; profile?: StockProfile | null; dailyBasic?: DailyBasic | null; events?: CompanyEvent[] | null; warnings?: WarningCode[] }
export type FetchDataRequest = { tsCodes?: string[] | null; include?: FetchInclude | null; limit?: FetchLimits | null }
export type FetchDataResponse = { errors?: ResponseError[]; items: FetchDataItem[] }
export type FetchInclude = { quote?: boolean | null; intraday?: boolean | null; klines?: KlinePeriod[] | null; minuteKlines?: MinuteKlinePeriod[] | null; indicators?: FetchIndicators | null; profile?: boolean | null; dailyBasic?: boolean | null; events?: boolean | null }
export type FetchIndicators = boolean | IndicatorName[]
export type FetchLimits = { kline?: number | null; minuteKline?: number | null; eventsDaysAhead?: number | null }
export type FetchNewsError = { field?: string | null; code: ErrorCode; message?: string | null }
export type FetchNewsItem = { id: string; source: string; title: string; summary?: string | null; url?: string | null; publishedAt?: string | null; articleExcerpt?: string | null; article?: ArticleSnippet | null; freshness?: NewsItemFreshness | null; warnings?: WarningCode[]; errors?: ErrorCode[] }
export type FetchNewsPage = { limit: number; offset: number; hasMore: boolean }
export type FetchNewsRequest = { 
/**
 * 按 newsId 列表精确取回（如 Runtime 装载 news buffer 批次）。
 * 可与 `query` / `sources` / 时间窗 AND 组合；上限 ≤200；未命中按缺失忽略。
 * Spec: news-module.md §4 `fetch_news`。
 */
ids?: string[] | null; query?: string | null; sources?: string[] | null; publishedFrom?: string | null; publishedTo?: string | null; includeArticle?: boolean | null; limit?: number | null; offset?: number | null; 
/**
 * 排序方向，默认 `desc`。详见 [`NewsOrder`] 与 spec §4 双向 keyset 读取。
 */
order?: NewsOrder | null }
export type FetchNewsResponse = { items: FetchNewsItem[]; errors: FetchNewsError[]; page: FetchNewsPage; 
/**
 * 按北京日期(YYYY-MM-DD)的每日真实总条数（同 filter，不受分页限制）。
 * 资讯页日期导航用它显示每天真实数量，而非分页累积。
 */
dateCounts?: NewsDateCount[] }
/**
 * spec §9 fetch_agent_state `include` 选择器（未选的段省略）。
 */
export type FetchStateInclude = { strategy?: boolean | null; runs?: boolean | null; analysisResults?: boolean | null; trades?: boolean | null; messages?: boolean | null; toolCalls?: boolean | null }
/**
 * spec §9 `FetchAgentStateRequest = { include?; limit?; offset? }`。
 */
export type FetchStateInput = { include?: FetchStateInclude | null; limit?: number | null; offset?: number | null }
/**
 * spec §9 `FetchInvestmentStrategyRequest = { status?; includeHistory? }`。
 */
export type FetchStrategyInput = { 
/**
 * 过滤：仅当 active 策略的 status 匹配时返回（None = 不过滤）。
 */
status?: StrategyStatus | null; 
/**
 * true = 附带 active strategyId 的历史版本列表。
 */
includeHistory?: boolean | null }
/**
 * spec §9 `FetchInvestmentStrategyResponse = { active?; history? }`。
 */
export type FetchStrategyResult = { active?: InvestmentStrategy | null; history?: StrategyHistoryEntry[] | null }
/**
 * Spec: shared-types.md §4
 * - `missing` 表示本地读模型没有可用数据，或数据已超过模块定义的硬过期阈值而不可再作为可用事实返回。
 * - `stale` 表示本地有数据，但不满足当前用途的新鲜度要求。
 * - Account 交易写路径必须 fail closed：`stale` / `missing` quote 不得成交。
 */
export type Freshness = { status: FreshnessStatus; capturedAt?: string | null; exchangeTime?: string | null; ageMs?: number | null; source?: string | null; warning?: WarningCode | null }
export type FreshnessStatus = "fresh" | "stale" | "missing"
/**
 * 单台 TDX HQ 站点的探测结果。
 */
export type HostProbe = { 
/**
 * 站点中文名（来自 `HQ_HOSTS`）。
 */
name: string; 
/**
 * IP / 域名。
 */
host: string; 
/**
 * 端口（默认 7709，个别 80）。
 */
port: number; 
/**
 * connect + handshake 往返延时（毫秒）；连不上 / 握手失败为 `None`。
 */
latencyMs: number | null; 
/**
 * 是否可达（探测成功）。
 */
ok: boolean; 
/**
 * 是否被选进当前 active 连接池（低延时子集）。
 */
inPool: boolean }
export type IndicatorBasis = { period: KlinePeriod; adjust: Adjust; fetchedAt: string }
/**
 * Spec: quotes-module.md §2
 */
export type IndicatorName = "ma_5" | "ma_10" | "ma_20" | "ma_60" | "ema_12" | "ema_26" | "macd_dif" | "macd_dea" | "macd_hist" | "rsi_6" | "rsi_12" | "rsi_24" | "kdj_k" | "kdj_d" | "kdj_j" | "boll_upper" | "boll_mid" | "boll_lower" | "volume_ma_5" | "volume_ma_10"
export type IndicatorSnapshot = { tsCode: TsCode; basis: IndicatorBasis; values: Partial<{ [key in string]: number | null }>; warnings?: WarningCode[] }
/**
 * Spec: quotes-module.md §4 `industry_heatmap`。
 */
export type IndustryHeatmap = { 
/**
 * 按 `avg_change_percent desc` 取前 N 个行业。
 */
topGainers: IndustryHeatmapItem[]; 
/**
 * 按 `avg_change_percent asc` 取前 N 个行业。
 */
topLosers: IndustryHeatmapItem[]; tradeDate: string; computedAt: string }
/**
 * Spec: quotes-module.md §4 `industry_heatmap` 单个行业项。
 */
export type IndustryHeatmapItem = { 
/**
 * 行业名称（来自 `MarketInstrument.sector`）。
 */
sector: string; 
/**
 * 该行业内有效 quote 标的的 `change_percent` 算术平均（百分点）。
 */
avgChangePercent: number; 
/**
 * 该行业参与统计的有效 quote 标的数。
 */
count: number; 
/**
 * 涨幅 top 3 的 `ts_code`（按 `change_percent desc`；不足 3 个时返回全部）。
 */
leaderCodes: TsCode[]; 
/**
 * 与 `leader_codes` 对应的名称。
 */
leaderNames: string[] }
export type InstrumentCategory = "stock" | "index" | "fund"
/**
 * Spec: quotes-module.md §2 — universe 来源。
 * 
 * `Builtin` 表示 cold-start seed 行：在 process startup 时由 `seed_builtin_instruments`
 * 写入，仅作 diagnostic 用途。真实 provider refresh 完成后 source 会被覆盖（spec §5 step 0）。
 */
export type InstrumentSource = "builtin" | "tdx" | "eastmoney" | "tushare" | "mixed"
export type InstrumentStatus = "listed" | "suspended" | "delisted" | "unknown"
export type IntradaySeries = { tradeDate: string; points: MinutePoint[]; freshness: Freshness; warnings?: WarningCode[] }
/**
 * 投资策略（一段自然语言）——版本化，只在对话中用户确认后写。
 * 
 * Spec: agent-runtime-module.md §3 `InvestmentStrategy`
 * 
 * 本阶段纯自然语言（不结构化硬约束）；硬风控由 Account fail-closed + Runtime 编排兜底。
 */
export type InvestmentStrategy = { strategyId: string; version: number; 
/**
 * 自然语言：投资理念 / 选股 / 风控 / 仓位 / 止盈止损纪律。
 */
strategy: string; status: StrategyStatus; createdAt: string; updatedAt: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KlinePageResult = { added: number; hasMore: boolean }
/**
 * Spec: quotes-module.md §2
 */
export type KlinePeriod = "day" | "week" | "month"
export type KlinePoint = { date: string; open: Price; close: Price; high: Price; low: Price; volume?: Volume | null; amount?: Amount | null }
export type KlineSeries = { period: KlinePeriod; adjust: Adjust; points: KlinePoint[]; freshness: Freshness; warnings?: WarningCode[] }
export type ListAccountArchivesResponse = { archives: AccountArchive[] }
export type ListMarketItem = ({ tsCode: TsCode; name: string; category: InstrumentCategory; market: Market; board?: string | null; sector?: string | null; status?: InstrumentStatus | null; isSt?: boolean | null; publisher?: string | null; indexCategory?: string | null; fundType?: string | null; management?: string | null; listDate?: string | null; source: InstrumentSource; updatedAt: string }) & { quote?: ListMarketQuoteSummary | null; quoteFreshness?: Freshness | null; warnings?: WarningCode[] }
export type ListMarketPage = { limit: number; offset: number; hasMore: boolean }
export type ListMarketQuoteSummary = { tradeDate?: string | null; price?: number | null; change?: number | null; changePercent?: number | null; open?: number | null; high?: number | null; low?: number | null; previousClose?: number | null; volume?: number | null; amount?: number | null }
export type ListMarketRequest = { category?: InstrumentCategory | null; query?: string | null; includeQuote?: boolean | null; sort?: ListMarketSort | null; limit?: number | null; offset?: number | null }
export type ListMarketResponse = { items: ListMarketItem[]; page: ListMarketPage }
export type ListMarketSort = "default" | "changePercentDesc" | "changePercentAsc" | "amountDesc"
export type ListNewsSourcesResponse = { items: NewsSource[] }
export type MarkTriggerHandledRequest = { triggerId: string; reason: string }
export type MarkTriggerHandledResponse = { accepted: boolean; trigger?: AccountTrigger | null; accountEventIds?: string[]; reason?: ErrorCode | null; message?: string | null }
export type Market = "SH" | "SZ" | "BJ"
/**
 * Spec: quotes-module.md §4 `market_breadth`。
 * 
 * 全市场宽度统计；按 spec 只统计 `category == stock`（不含指数、基金）。
 * 计算前必须先用 quote 有效性规则筛掉无可用 quote 或不匹配 eligible
 * trade date 的标的，这些归入 `no_data`。
 */
export type MarketBreadth = { 
/**
 * 有效 quote 的标的总数。`up + down + flat == total`。
 */
total: number; 
/**
 * `change_percent > 0` 的家数。
 */
up: number; 
/**
 * `change_percent < 0` 的家数。
 */
down: number; 
/**
 * `change_percent == 0`（或缺失但 quote 仍有效）的家数。
 */
flat: number; 
/**
 * 涨停家数（按本模块顶部阈值规则）。是 `up` 的子集。
 */
limitUp: number; 
/**
 * 跌停家数（按本模块顶部阈值规则）。是 `down` 的子集。
 */
limitDown: number; 
/**
 * universe 中没有有效 quote 的标的数（snapshot missing / expired / 非 stock category 不计入此数）。
 */
noData: number; 
/**
 * 本次统计使用的 eligible trade date。
 */
tradeDate: string; 
/**
 * 计算完成时间。
 */
computedAt: string }
/**
 * 消息种类（spec §2 `AgentMessage.kind`）。
 * 
 * Spec: agent-infra-module.md §2
 * - `Chat`（默认）= 普通对话消息。
 * - `Summary` = §4 Summarize 产出的压缩检查点；durable，不再被 MicroClear / Drop / 再次 Summarize 触碰。
 */
export type MessageKind = "chat" | "summary"
export type MinuteKlinePeriod = "1m" | "5m" | "15m" | "30m" | "60m"
export type MinuteKlinePoint = { timestampMs: number; open: Price; close: Price; high: Price; low: Price; volume: Volume; amount: Amount }
export type MinuteKlineSeries = { period: MinuteKlinePeriod; points: MinuteKlinePoint[]; freshness: Freshness; warnings?: WarningCode[] }
export type MinutePoint = { tradeDate: string; time: string; price: Price; average?: Price | null; volume?: Volume | null; amount?: Amount | null }
/**
 * CNY，保留到分；内部计算可使用更高精度。
 */
export type Money = string
export type NewsDateCount = { date: string; count: number }
/**
 * 单 provider / source 失败（shared-types.md §6 NewsFailure）。
 */
export type NewsFailure = { provider: string; source?: string | null; code: ErrorCode; message?: string | null; details?: JsonValue | null; stage?: NewsRefreshStage | null; retryable?: boolean | null; occurredAt: string }
export type NewsItemFreshness = { ageMs?: number | null; articleFetchedAt?: string | null }
/**
 * 排序方向。默认语义 `Desc`（最新在前）。`Asc` 专供前端「往上滑加载更新」的
 * keyset 游标（升序取紧邻最新一条之上的一页，前端 reverse 后 prepend）。
 * 
 * Spec: news-module.md §4 fetch_news（`order` 语义 + 双向 keyset 读取）。
 */
export type NewsOrder = "desc" | "asc"
/**
 * Refresh stage（spec §4 / §5）。
 */
export type NewsRefreshStage = "fetch" | "normalize" | "save" | "article"
/**
 * 单条 item 跳过 / partial 提示（shared-types.md §6 NewsRefreshWarning）。
 */
export type NewsRefreshWarning = { provider: string; source?: string | null; code: WarningCode; message?: string | null; stage?: NewsRefreshStage | null; skippedCount?: number | null; occurredAt: string }
/**
 * `source_id` 由 `namespace:channel` 形式构成；与 `NewsItem.source` 完全一致。
 */
export type NewsSource = { sourceId: string; provider: string; displayName?: string | null; enabled: boolean; dynamic?: boolean | null; lastRefreshAt?: string | null; lastError?: NewsSourceLastError | null }
export type NewsSourceLastError = { code: ErrorCode; message?: string | null; occurredAt: string }
/**
 * Spec: account-module.md §2 订单模型
 */
export type Order = { orderId: string; 
/**
 * 调用方幂等键（spec §4 line122）；持久化供反查。Agent 单经 operate_account_with_dedup 盖戳；
 * 内部 system 订单 / 旧单为 None。
 */
clientOrderId?: string | null; tsCode: TsCode; side: OrderSide; orderType: OrderType; limitPrice?: Price | null; quantity: Shares; filledQuantity: Shares; status: OrderStatus; intent: OrderIntent; positionId?: string | null; reason?: string | null; actor: TradingActor; createdAt: string; updatedAt: string; expiresAt?: string | null }
export type OrderIntent = "open_position" | "scale_in" | "scale_out" | "close_position" | "direct_order"
export type OrderSide = "buy" | "sell"
export type OrderStatus = "pending" | "partially_filled" | "filled" | "cancelled" | "rejected" | "expired"
export type OrderType = "market" | "limit"
export type PingResult = { ok: boolean; message: string }
/**
 * Spec: account-module.md §2 仓位模型
 */
export type Position = { positionId: string; tsCode: TsCode; name: string; status: PositionStatus; quantity: Shares; sellableQuantity: Shares; avgCost: Price; marketPrice?: Price | null; marketValue?: Money | null; quoteFreshness?: Freshness | null; realizedPnl: Money; unrealizedPnl?: Money | null; openedAt: string; closedAt?: string | null; protection?: PositionProtection | null; actor: TradingActor; reasoning?: string | null; warnings?: WarningCode[] }
/**
 * Spec: account-module.md §2 保护条件模型
 */
export type PositionProtection = { stopLoss?: Price | null; takeProfit?: Price | null; timeStopAt?: string | null; invalidationSignals?: string[]; enabled: boolean; revision: number; updatedAt: string }
export type PositionStatus = "open" | "closed"
export type PositionStatusFilter = "open" | "closed" | "all"
/**
 * CNY / 股或份。
 */
export type Price = string
/**
 * 渠道视图 —— **屏蔽 apiKey 明文**，只回 `apiKeySet: bool`。
 * 
 * Spec §2：apiKey 只写不读；list / get DTO 必须屏蔽明文。
 */
export type ProviderChannelView = { channelId: string; provider: string; wireFormat: WireFormat; baseUrl?: string | null; model: string; enabled: boolean; isActive: boolean; 
/**
 * apiKey 是否已设置（永远不回传明文）。
 */
apiKeySet: boolean }
/**
 * Spec: quotes-module.md §2 行情 DTO
 */
export type QuoteDepthLevel = { price?: Price | null; volume?: Volume | null }
/**
 * Spec: quotes-module.md §2 行情 DTO
 */
export type QuoteSource = "tdx" | "eastmoney" | "tencent" | "sina" | "mixed"
/**
 * Response 级 / item 级错误条目。
 * 
 * Spec: docs/design/quotes-module.md §4 `ResponseError`；shared-types.md §5。
 * 跨 BC 复用（News / Account / Quotes 都可以返回）。
 */
export type ResponseError = { code: ErrorCode; message?: string | null; field?: string | null; tsCode?: TsCode | null }
export type ReviewReportRef = { name: string; path: string }
export type RunReviewInput = { 
/**
 * 复盘交易日（YYYYMMDD 或 YYYY-MM-DD）。
 */
tradeDate: string }
export type RunReviewResult = { runId: string; reportPath?: string | null }
export type ScanCondition = { field: ScanConditionField; op: ScanOp; value: ScanConditionValue }
export type ScanConditionField = "change_percent" | "amount" | "volume" | "turnover_rate" | "volume_ratio" | "pe_ttm" | "pb" | "total_mv" | "circ_mv"
export type ScanConditionValue = number | [number, number]
export type ScanCriteria = { filter?: string | null; conditions?: ScanCondition[] | null; sortBy?: string | null; limit: number }
export type ScanFilter = "limit_up" | "limit_down" | "top_gain" | "top_loss" | "top_amount" | "top_volume"
export type ScanItem = { rank: number; tsCode: TsCode; name?: string | null; category: InstrumentCategory; quote?: StockQuote | null; dailyBasic?: DailyBasic | null; warnings?: WarningCode[] }
export type ScanMarketRequest = { category?: InstrumentCategory | null; filter?: ScanFilter | null; conditions?: ScanCondition[] | null; sortBy?: ScanSortBy | null; limit?: number | null }
export type ScanMarketResponse = ({ generatedAt: string; universe: ScanUniverse; criteria: ScanCriteria; items: ScanItem[]; warnings?: WarningCode[] }) & { errors?: ResponseError[] }
export type ScanOp = "gt" | "gte" | "lt" | "lte" | "eq" | "between"
export type ScanSortBy = "change_pct_desc" | "change_pct_asc" | "amount_desc" | "volume_desc" | "turnover_rate_desc"
export type ScanUniverse = { category?: InstrumentCategory | null; total: number; validQuoteCount?: number | null; excludedMissingQuoteCount?: number | null; excludedExpiredQuoteCount?: number | null; matched: number }
/**
 * spec §9 `SendAgentMessageRequest = { content; images?; conversationId? }`。
 * 
 * `conversationId?`（spec §9 补充）：dialogue 是独立连续对话线程（§3），传入续接已有线程；
 * 不传则后端新开一个匿名线程。
 */
export type SendMessageInput = { 
/**
 * 用户消息文本（spec `content`）。
 */
content: string; 
/**
 * 多模态附件（base64/URL）；当前 loop 仅消费文本，images 接受但未透传（见模块注）。
 */
images?: string[] | null; 
/**
 * 续接的对话线程 id（spec §9 补充）；不传则后端新开匿名线程。
 */
conversationId?: string | null }
/**
 * spec §9 `SendAgentMessageResponse = { messageId; runId }`。
 */
export type SendMessageResult = { messageId: string; runId: string }
export type SetNewsAutoAnalysisResult = { enabled: boolean; 
/**
 * false→true 开启时回填最近窗口内 news 入 buffer 的条数（spec §5）。
 */
backfilled: number }
/**
 * 股 / 份数量。
 * 
 * Spec: shared-types.md §2
 * - Account 写接口必须校验 `Shares` 为正数；股票和场内基金买卖数量必须是 100 股 / 份整数倍。
 * （正数 / 整手校验由 Account domain 实现，本类型仅承载数值。）
 */
export type Shares = number
/**
 * Tool 副作用分类（spec §2 `SideEffect`）。
 */
export type SideEffect = "none" | "non_trading_write" | "trading_write"
/**
 * Spec: quotes-module.md §2 — fetch_data profile 投影。
 */
export type StockProfile = { tsCode: TsCode; name: string; category: InstrumentCategory; market: Market; board?: string | null; sector?: string | null; status?: InstrumentStatus | null; isSt?: boolean | null; listDate?: string | null }
/**
 * Spec: quotes-module.md §2 StockQuote
 */
export type StockQuote = { tsCode: TsCode; name?: string | null; category: InstrumentCategory; tradeDate: string; price?: Price | null; previousClose?: Price | null; open?: Price | null; high?: Price | null; low?: Price | null; change?: Price | null; changePercent?: number | null; volume?: Volume | null; amount?: Amount | null; turnoverRate?: number | null; volumeRatio?: number | null; limitUp?: Price | null; limitDown?: Price | null; bid?: QuoteDepthLevel[]; ask?: QuoteDepthLevel[]; tradeStatus: TradeStatus; source: QuoteSource; capturedAt: string; exchangeTime?: string | null; freshness: Freshness; warnings?: WarningCode[] }
/**
 * spec §9 历史版本条目。
 */
export type StrategyHistoryEntry = { version: number; updatedAt: string; reason: string }
export type StrategyStatus = "active" | "paused"
/**
 * 一次 tool 调用审计。
 * 
 * Spec: agent-infra-module.md §2 `ToolCall`
 * 
 * PayloadStore 双层存储规则：
 * - input / output JSON 序列化后 ≤ 8KB 时 `inputSummary` = 完整 payload，`inputPayloadRef = None`。
 * - > 8KB 时 `inputSummary` 是截断摘要（前 1KB + `"[truncated, see ref]"`），完整数据通过 ref。
 */
export type ToolCall = { toolCallId: string; runId: string; name: string; inputSummary: JsonValue; inputPayloadRef?: string | null; outputSummary?: JsonValue | null; outputPayloadRef?: string | null; isError: boolean; errorCode?: ErrorCode | null; startedAt: string; endedAt?: string | null; durationMs?: number | null }
/**
 * 一个 Tool 的协议描述。
 * 
 * Spec: agent-infra-module.md §2 `ToolSpec`
 * 
 * 规则（来自 spec §2）：
 * - 同名 tool 只能注册一次；重复注册必须 fail closed。
 * - `examples` 至少 1 个完整 `<use_tool ...>{...}</use_tool>` 示例字符串。
 * - description 应当能被产品负责人手写为 markdown。
 */
export type ToolSpec = { name: string; description: string; 
/**
 * JSON Schema（dispatch 前校验）。
 */
inputSchema: JsonValue; examples: string[]; sideEffect: SideEffect; timeoutMs: number; 
/**
 * fork 类工具标记（`run_subagent` / `run_skill` 等）。
 * 
 * 构造子 run registry 时**按此剔除**（spec §3.5 无嵌套，不靠 name 白名单），
 * 确保任何新增 fork 类工具（含 Runtime 注入的领域 fork 工具）都被覆盖。缺省 false。
 */
isSpawn?: boolean }
/**
 * Spec: quotes-module.md §2 — query facade 派生 trade status。
 */
export type TradeStatus = "trading" | "halted" | "closed" | "unknown"
/**
 * Trading actor — 当前订单 / 仓位只能由 `agent` 发起。
 * 
 * Spec: account-module.md §2 actor 命名规则。
 */
export type TradingActor = "agent"
export type TriggerHandledAll = "all"
export type TriggerHandledFilter = boolean | TriggerHandledAll
/**
 * 跨模块主键。格式：6 位数字 + `.` + 市场后缀（`600519.SH` / `000001.SZ` / `430047.BJ`）。
 * 
 * Spec: shared-types.md §1
 * - 匹配大小写不敏感，但对外返回必须大写。
 * - 非 `TsCode` 标识不能作为跨模块持久化主键。
 */
export type TsCode = string
/**
 * 编辑已有渠道的请求 —— 按 channelId 更新可编辑字段。
 * 
 * Spec §5 前端命令：`agent_update_channel`。apiKey 为空/省略 = 保留原 key 不变；
 * 不修改 is_active；未暴露的能力字段（thinking budget 等）保留原值。
 */
export type UpdateChannelInput = { channelId: string; provider: string; wireFormat: WireFormat; baseUrl?: string | null; model: string; 
/**
 * 空/省略 = 保留原 key；非空才覆盖。
 */
apiKey?: string | null; enabled?: boolean | null; supportsVision?: boolean | null; supportsThinking?: boolean | null; maxOutputTokens?: number | null; contextWindowTokens?: number | null }
export type UpdateWatchlistRequest = ({ action: "add"; ts_code: TsCode; note?: string | null; reason?: string | null } | { action: "remove"; ts_code: TsCode; reason?: string | null } | { action: "update_note"; ts_code: TsCode; note?: string | null; reason?: string | null })
export type UpdateWatchlistResponse = { accepted: boolean; reason?: ErrorCode | null; message?: string | null; item?: WatchlistItem | null; accountEventIds: string[]; warnings?: WarningCode[] }
/**
 * spec §9 `UpsertInvestmentStrategyRequest = { strategyId?; baseVersion?; strategy; status; reason }`。
 */
export type UpsertStrategyInput = { 
/**
 * 目标策略 id；不传 = 更新当前 active 策略的 id（无 active 时用 baseline id）。
 */
strategyId?: string | null; 
/**
 * 乐观并发基线版本（前端拿当前 active.version 回填）；不传 = 不校验。
 */
baseVersion?: number | null; 
/**
 * 策略自然语言全文。
 */
strategy: string; 
/**
 * 写入后状态（spec：`"active" | "paused"`）。
 */
status: StrategyStatus; 
/**
 * 写入理由（审计）。
 */
reason: string }
export type UpsertStrategyResult = { strategyId: string; version: number }
/**
 * 成交量，股或份。Provider 单位必须 normalize 到最小交易数量单位，不使用"手"。
 */
export type Volume = number
export type WarmArticlesErr = { ok: false; error: WarmArticlesError }
/**
 * `warm_articles` 失败 error（spec §5）。
 */
export type WarmArticlesError = { code: ErrorCode; field?: WarmArticlesErrorField | null; message?: string | null }
export type WarmArticlesErrorField = "newsIds" | "recentLimit"
export type WarmArticlesOk = { ok: true; result: WarmArticlesResult }
export type WarmArticlesRequest = { newsIds?: string[] | null; recentLimit?: number | null; force?: boolean | null }
export type WarmArticlesResponse = WarmArticlesOk | WarmArticlesErr
export type WarmArticlesResult = { batchId: string; requestedCount: number; attemptedCount: number; articleUpdatedCount: number; articleUpdatedNewsIds: string[]; warnings: NewsRefreshWarning[]; failures: NewsFailure[] }
export type WarningCode = "quote_missing" | "quote_stale" | "snapshot_expired" | "quote_price_missing" | "depth_missing" | "instrument_missing" | "provider_partial_failure" | "article_missing" | "qfq_missing" | "using_unadjusted_kline" | "daily_basic_missing" | "events_missing" | "strategy_omitted" | "mapping_missing" | "data_partial"
/**
 * Spec: account-module.md §2 自选模型
 */
export type WatchlistItem = { tsCode: TsCode; name?: string | null; addedAt: string; note?: string | null }
/**
 * 自选展示模型：WatchlistItem + 可选 quote。
 * 
 * Spec: account-module.md §4 fetch_account.include.watchlist
 */
export type WatchlistItemView = ({ tsCode: TsCode; name?: string | null; addedAt: string; note?: string | null }) & { quote?: WatchlistQuoteView | null }
/**
 * 自选行情字段。来自 Quotes snapshot；不存在时 freshness = missing。
 * 
 * Spec: account-module.md §4 (fetch_account watchlist quote 字段)
 */
export type WatchlistQuoteView = { price?: Price | null; changePercent?: number | null; volume?: Volume | null; amount?: Amount | null; source?: string | null; freshness?: Freshness | null }
/**
 * Wire format 标识 — channel adapter 选择哪个 provider 实现。
 */
export type WireFormat = 
/**
 * Anthropic `/v1/messages`
 */
"messages" | 
/**
 * OpenAI `/v1/responses`
 */
"responses" | 
/**
 * OpenAI-compatible `/v1/chat/completions`
 */
"chat_completions"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
