// AUTO-GENERATED by tauri-specta during `cargo run` / `tauri dev`.
//
// 此文件由后端 lib.rs::run() 中的 specta builder 输出。第一次启动后端后会被覆盖。
// Phase 0 占位仅用于让 `npm run build` 在第一次启动后端前也能通过。

import { invoke as tauriInvoke } from "@tauri-apps/api/core";

export type CommandResult<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

export type ErrorCode = string;

export type CommandError = {
  code: ErrorCode;
  message?: string;
  details?: unknown;
};

export type PingResult = {
  ok: boolean;
  message: string;
};

async function call<T, E>(cmd: string, args?: Record<string, unknown>): Promise<CommandResult<T, E>> {
  try {
    const data = (await tauriInvoke(cmd, args ?? {})) as T;
    return { status: "ok", data };
  } catch (err) {
    return { status: "error", error: err as E };
  }
}

export const commands = {
  ping: () => call<PingResult, CommandError>("ping"),
};
