
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<Result<PingResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExternal(url: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_external", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 同步读取 News 本地读模型。
 * 
 * Spec: news-module.md §4 fetch_news
 */
async fetchNews(request: FetchNewsRequest) : Promise<Result<FetchNewsResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_news", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出当前已知 source。
 * 
 * Spec: news-module.md §4 list_news_sources
 */
async listNewsSources() : Promise<Result<ListNewsSourcesResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_news_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 显式 warm articles。
 * 
 * Spec: news-module.md §5 warm_articles
 */
async warmArticles(request: WarmArticlesRequest) : Promise<Result<WarmArticlesResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warm_articles", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMarket(request: ListMarketRequest) : Promise<Result<ListMarketResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_market", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchData(request: FetchDataRequest) : Promise<Result<FetchDataResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_data", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanMarket(request: ScanMarketRequest) : Promise<Result<ScanMarketResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_market", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 市场宽度（spec §4 `market_breadth`）。
 * 
 * 纯只读聚合，不触发 provider；只统计 `category == stock`。
 */
async fetchMarketBreadth() : Promise<Result<MarketBreadth, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_market_breadth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 行业热度（spec §4 `industry_heatmap`）。
 * 
 * `top_n` 缺省时使用 5；上限 50（防止 UI 误传大值）。
 */
async fetchIndustryHeatmap(topN: number | null) : Promise<Result<IndustryHeatmap, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_industry_heatmap", { topN }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端 on-demand 拉数据：用户选中标的 + 切到某 chart period 时，如果 DB 空就触发后端拉一份。
 * 
 * 按 period 字符串分派：
 * - `"day"` / `"week"` / `"month"` → `refresh_klines`
 * - `"1m"` / `"5m"` / `"15m"` / `"30m"` / `"60m"` → `refresh_minute_klines`
 * - `"intraday"` → `refresh_intraday`
 * 
 * 同步等待 refresh 完成；调用方拿到 Ok 后可以再次调用 fetch_data 拿数据。
 * 
 * 已有数据时也会重新拉（refresh 是 upsert，幂等）；UI 调用方决定是否要重新触发。
 */
async ensureChartData(tsCode: string, period: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_chart_data", { tsCode, period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 前端左拉到尽头时触发：扩展该 ts_code 的历史 K 线深度到 `target_days`。
 * 
 * - `target_days <= TDX_SINGLE_FETCH_LIMIT (800)`：走 TDX 主路径（最多 ~3 年）
 * - `target_days > 800` 且 TushareHealthState.isAvailable：走 TuShare 长历史扩展段
 * - 否则 silent skip 长历史
 * 
 * `period` 字符串："day" / "week" / "month"。分钟 K 不走此命令（TDX 限 800 根，分钟 K 一天就 240 根）。
 * 
 * Spec: docs/design/quotes-module.md §4 + §5 K 线长历史
 */
async extendChartHistory(tsCode: string, period: string, targetDays: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extend_chart_history", { tsCode, period, targetDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 拉一页 K 线（渐进式加载用）。`start_offset` 为从最新往回跳过的根数：
 * - 0 = 最新一批
 * - 800 = 再往前一批
 * - ...
 * 
 * 后端 upsert 写 DB 后返回 `(addedCount, hasMore)`。前端先拉 start=0 显示首屏，
 * 再 background loop 800/1600/... applyMoreData，直到 hasMore=false 停。
 * 
 * 仅支持 day/week/month；分钟 K 不需要分页（一次 800 根足够）。
 */
async fetchKlinePage(tsCode: string, period: string, startOffset: number) : Promise<Result<KlinePageResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_kline_page", { tsCode, period, startOffset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 声明热点集（spec §5 热点档）：前端把自选 + 可见列表 top-N + 关注标的传入，
 * scheduler 的 3s tick 会高频刷这批（≤120）。非法 ts_code 跳过。
 */
async setQuoteHotset(tsCodes: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_quote_hotset", { tsCodes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 聚焦按需刷新一批 quotes（spec §5「实时行情（聚焦按需）」）：前端把当前关注的标的
 * （自选 / 可见列表 / 详情）传入，后端按新鲜度跳过 + 80/批并发跑连接池刷 `MARKET_SNAPSHOT`，
 * 通过 `market-quotes-refresh-progress`(scope=subscribed) 增量推回前端。非法 ts_code 跳过。
 */
async refreshQuotes(tsCodes: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_quotes", { tsCodes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Frontend log forwarder：前端调 commands.forwardLog(msg) → 后端 tracing
 * → tauri dev stdout，可以从开发者那里直接读 log 文件分析性能问题。
 * 仅供 dev / 调试用，生产 build 可去掉。
 */
async forwardLog(level: string, message: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forward_log", { level, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出当前 ToolRegistry 已注册的 tool。
 * 
 * Spec: agent-infra-module.md §5 Tool Registry API（snapshot）
 */
async agentListTools() : Promise<Result<ToolSpec[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_tools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 返回内置快速预设（DeepSeek / OpenAI / Anthropic 官方）。
 * 
 * Spec §5 前端命令：`agent_channel_presets`
 */
async agentChannelPresets() : Promise<Result<ChannelPresetView[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_channel_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 调对应 wireFormat 的 `/models` 接口发现可用模型。
 * 
 * Spec §5 模型发现 API：发现失败时调用方引导用户手填模型名。
 */
async agentDiscoverModels(wireFormat: WireFormat, baseUrl: string, apiKey: string) : Promise<Result<DiscoveredModel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_discover_models", { wireFormat, baseUrl, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 添加一条渠道。生成 channelId（`ch_<uuid>`），stream=true，能力缺省 false。
 * 若是首条渠道，自动设为 active。
 * 
 * Spec §2：每个确认保留的模型各成一条 ProviderChannel；维护 active 渠道。
 */
async agentAddChannel(input: AddChannelInput) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_add_channel", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 编辑已有渠道（按 channelId）。apiKey 为空/省略保留原 key；不改 is_active；
 * 未暴露字段保留原值。channelId 不存在 → not_found。
 * 
 * Spec §5 前端命令：`agent_update_channel`
 */
async agentUpdateChannel(input: UpdateChannelInput) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_update_channel", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出所有渠道（**屏蔽 apiKey 明文**）。
 * 
 * Spec §5 前端命令：`agent_list_channels`（屏蔽 apiKey）
 */
async agentListChannels() : Promise<Result<ProviderChannelView[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_list_channels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除一条渠道。
 */
async agentRemoveChannel(channelId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_remove_channel", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 设置当前 active 渠道。
 * 
 * Spec §5 前端命令：`agent_set_active_channel`
 */
async agentSetActiveChannel(channelId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_set_active_channel", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取当前 active 渠道（屏蔽 apiKey）。
 */
async agentGetActiveChannel() : Promise<Result<ProviderChannelView | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_get_active_channel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchAccount(request: FetchAccountRequest) : Promise<Result<FetchAccountResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_account", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWatchlist(request: UpdateWatchlistRequest) : Promise<Result<UpdateWatchlistResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_watchlist", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markTriggerHandled(request: MarkTriggerHandledRequest) : Promise<Result<MarkTriggerHandledResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_trigger_handled", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildAccountSnapshot() : Promise<Result<AccountSnapshot, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_account_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Spec: account-module.md §2 AccountEvent。
 */
export type AccountEvent = { eventId: string; eventType: AccountEventType; orderId?: string | null; fillId?: string | null; positionId?: string | null; tsCode?: TsCode | null; reason?: string | null; 
/**
 * `agent` | `system` | `user`（AccountActor）。
 */
actor: string; payload: JsonValue; occurredAt: string }
/**
 * Spec: account-module.md §2 AccountEventType。
 */
export type AccountEventType = "account_initialized" | "order_placed" | "order_cancelled" | "order_rejected" | "order_expired" | "order_partially_filled" | "order_filled" | "position_opened" | "position_scaled" | "position_closed" | "protection_adjusted" | "watchlist_added" | "watchlist_removed" | "watchlist_note_updated" | "cash_frozen" | "cash_released" | "shares_frozen" | "shares_released" | "invalidation_signal_recorded" | "trigger_created" | "trigger_handled" | "snapshot_rebuilt"
/**
 * Spec: account-module.md §2 账户快照
 */
export type AccountSnapshot = { initialCash: Money; cash: Money; availableCash: Money; frozenCash: Money; marketValue: Money; totalAssets: Money; realizedPnl: Money; unrealizedPnl: Money; totalPnl: Money; pricedPositionCount: number; unpricedPositionCount: number; valuationFreshness: Freshness; openPositionCount: number; pendingOrderCount: number; capturedAt: string; warnings?: WarningCode[] }
/**
 * Spec: account-module.md §2 AccountTrigger。
 */
export type AccountTrigger = { triggerId: string; triggerType: AccountTriggerType; orderId?: string | null; positionId?: string | null; tsCode?: TsCode | null; price?: Price | null; 
/**
 * 触发阈值（字符串编码），可表示 Price / OccurredAt / signal label。
 */
threshold?: string | null; quoteFreshness?: Freshness | null; warnings?: WarningCode[]; eventId: string; handled: boolean; occurredAt: string }
export type AccountTriggerType = "stop_loss" | "take_profit" | "time_stop" | "order_filled" | "order_rejected" | "order_expired" | "invalidated"
/**
 * 添加渠道的请求 —— 一条确认保留的模型成一条渠道。
 */
export type AddChannelInput = { 
/**
 * 用户输入的渠道名（展示用 provider name）。
 */
provider: string; wireFormat: WireFormat; baseUrl?: string | null; apiKey: string; model: string; 
/**
 * 可选能力标记；缺省 false。
 */
supportsVision?: boolean | null; supportsThinking?: boolean | null; maxOutputTokens?: number | null; contextWindowTokens?: number | null }
export type Adjust = "none" | "qfq" | "hfq"
/**
 * 成交额，CNY。
 */
export type Amount = string
export type ArticleSnippet = { title?: string | null; content: string; fetchedAt?: string | null }
/**
 * 快速预设视图（返回给设置页）。
 */
export type ChannelPresetView = { key: string; provider: string; wireFormat: WireFormat; baseUrl: string }
export type CommandError = { code: ErrorCode; message?: string | null; details?: JsonValue | null }
/**
 * Spec: quotes-module.md §2 CompanyEvent
 */
export type CompanyEvent = { id: string; tsCode: TsCode; eventType: CompanyEventType; announceDate?: string | null; effectiveDate?: string | null; payload: JsonValue; source: string; fetchedAt: string }
export type CompanyEventType = "dividend" | "suspension" | "resume" | "st" | "earnings_forecast" | "unlock" | "other"
/**
 * Spec: quotes-module.md §2 基本面读模型
 */
export type DailyBasic = { tsCode: TsCode; tradeDate: string; pe?: number | null; peTtm?: number | null; pb?: number | null; ps?: number | null; psTtm?: number | null; turnoverRate?: number | null; turnoverRateFloat?: number | null; volumeRatio?: number | null; totalMv?: Money | null; circMv?: Money | null; source: string; fetchedAt: string }
/**
 * 发现到的单个可用模型。
 */
export type DiscoveredModel = { id: string; displayName?: string | null }
export type ErrorCode = "invalid_input" | "not_found" | "provider_unavailable" | "rate_limited" | "db_error" | "parse_error" | "quote_missing" | "quote_stale" | "quote_price_missing" | "depth_missing" | "outside_trading_session" | "instrument_not_tradable" | "instrument_suspended" | "limit_up_down_blocked" | "insufficient_cash" | "insufficient_sellable_quantity" | "invalid_lot_size" | "order_not_pending" | "risk_limit_exceeded" | "strategy_required" | "duplicate_event" | "version_conflict" | "article_extract_failed" | "tool_timeout" | "provider_context_too_long" | 
/**
 * 本地写 tool（write_file / edit_file）的 path 规范化后越界 <workspace>。
 * Spec: agent-runtime-module.md §4.2 本地通用 tool 契约（建议 A）。
 */
"path_outside_workspace" | 
/**
 * run_bash 命中危险命令门禁被拒（约定级，非强隔离）。
 * Spec: agent-runtime-module.md §2 run_bash 危险命令门禁 / §4.2。
 */
"command_rejected"
export type FetchAccountInclude = { snapshot?: boolean | null; positions?: boolean | null; orders?: boolean | null; watchlist?: boolean | null; events?: boolean | null; triggers?: boolean | null }
export type FetchAccountRequest = { include?: FetchAccountInclude | null; positionStatus?: PositionStatusFilter | null; orderActive?: boolean | null; orderStatusIn?: OrderStatus[] | null; triggerHandled?: TriggerHandledFilter | null; limit?: number | null; offset?: number | null }
export type FetchAccountResponse = { snapshot?: AccountSnapshot | null; positions?: Position[] | null; orders?: Order[] | null; watchlist?: WatchlistItemView[] | null; events?: AccountEvent[] | null; triggers?: AccountTrigger[] | null; warnings?: WarningCode[] }
export type FetchDataItem = { tsCode: TsCode; category: InstrumentCategory; name?: string | null; quote?: StockQuote | null; quoteFreshness?: Freshness | null; intraday?: IntradaySeries | null; klines?: Partial<{ [key in string]: KlineSeries }> | null; minuteKlines?: Partial<{ [key in string]: MinuteKlineSeries }> | null; indicators?: IndicatorSnapshot | null; profile?: StockProfile | null; dailyBasic?: DailyBasic | null; events?: CompanyEvent[] | null; warnings?: WarningCode[] }
export type FetchDataRequest = { tsCodes?: string[] | null; include?: FetchInclude | null; limit?: FetchLimits | null }
export type FetchDataResponse = { errors?: ResponseError[]; items: FetchDataItem[] }
export type FetchInclude = { quote?: boolean | null; intraday?: boolean | null; klines?: KlinePeriod[] | null; minuteKlines?: MinuteKlinePeriod[] | null; indicators?: FetchIndicators | null; profile?: boolean | null; dailyBasic?: boolean | null; events?: boolean | null }
export type FetchIndicators = boolean | IndicatorName[]
export type FetchLimits = { kline?: number | null; minuteKline?: number | null; eventsDaysAhead?: number | null }
export type FetchNewsError = { field?: string | null; code: ErrorCode; message?: string | null }
export type FetchNewsItem = { id: string; source: string; title: string; summary?: string | null; url?: string | null; publishedAt?: string | null; articleExcerpt?: string | null; article?: ArticleSnippet | null; freshness?: NewsItemFreshness | null; warnings?: WarningCode[]; errors?: ErrorCode[] }
export type FetchNewsPage = { limit: number; offset: number; hasMore: boolean }
export type FetchNewsRequest = { query?: string | null; sources?: string[] | null; publishedFrom?: string | null; publishedTo?: string | null; includeArticle?: boolean | null; limit?: number | null; offset?: number | null; 
/**
 * 排序方向，默认 `desc`。详见 [`NewsOrder`] 与 spec §4 双向 keyset 读取。
 */
order?: NewsOrder | null }
export type FetchNewsResponse = { items: FetchNewsItem[]; errors: FetchNewsError[]; page: FetchNewsPage; 
/**
 * 按北京日期(YYYY-MM-DD)的每日真实总条数（同 filter，不受分页限制）。
 * 资讯页日期导航用它显示每天真实数量，而非分页累积。
 */
dateCounts?: NewsDateCount[] }
/**
 * Spec: shared-types.md §4
 * - `missing` 表示本地读模型没有可用数据，或数据已超过模块定义的硬过期阈值而不可再作为可用事实返回。
 * - `stale` 表示本地有数据，但不满足当前用途的新鲜度要求。
 * - Account 交易写路径必须 fail closed：`stale` / `missing` quote 不得成交。
 */
export type Freshness = { status: FreshnessStatus; capturedAt?: string | null; exchangeTime?: string | null; ageMs?: number | null; source?: string | null; warning?: WarningCode | null }
export type FreshnessStatus = "fresh" | "stale" | "missing"
export type IndicatorBasis = { period: KlinePeriod; adjust: Adjust; fetchedAt: string }
/**
 * Spec: quotes-module.md §2
 */
export type IndicatorName = "ma_5" | "ma_10" | "ma_20" | "ma_60" | "ema_12" | "ema_26" | "macd_dif" | "macd_dea" | "macd_hist" | "rsi_6" | "rsi_12" | "rsi_24" | "kdj_k" | "kdj_d" | "kdj_j" | "boll_upper" | "boll_mid" | "boll_lower" | "volume_ma_5" | "volume_ma_10"
export type IndicatorSnapshot = { tsCode: TsCode; basis: IndicatorBasis; values: Partial<{ [key in string]: number | null }>; warnings?: WarningCode[] }
/**
 * Spec: quotes-module.md §4 `industry_heatmap`。
 */
export type IndustryHeatmap = { 
/**
 * 按 `avg_change_percent desc` 取前 N 个行业。
 */
topGainers: IndustryHeatmapItem[]; 
/**
 * 按 `avg_change_percent asc` 取前 N 个行业。
 */
topLosers: IndustryHeatmapItem[]; tradeDate: string; computedAt: string }
/**
 * Spec: quotes-module.md §4 `industry_heatmap` 单个行业项。
 */
export type IndustryHeatmapItem = { 
/**
 * 行业名称（来自 `MarketInstrument.sector`）。
 */
sector: string; 
/**
 * 该行业内有效 quote 标的的 `change_percent` 算术平均（百分点）。
 */
avgChangePercent: number; 
/**
 * 该行业参与统计的有效 quote 标的数。
 */
count: number; 
/**
 * 涨幅 top 3 的 `ts_code`（按 `change_percent desc`；不足 3 个时返回全部）。
 */
leaderCodes: TsCode[]; 
/**
 * 与 `leader_codes` 对应的名称。
 */
leaderNames: string[] }
export type InstrumentCategory = "stock" | "index" | "fund"
/**
 * Spec: quotes-module.md §2 — universe 来源。
 * 
 * `Builtin` 表示 cold-start seed 行：在 process startup 时由 `seed_builtin_instruments`
 * 写入，仅作 diagnostic 用途。真实 provider refresh 完成后 source 会被覆盖（spec §5 step 0）。
 */
export type InstrumentSource = "builtin" | "tdx" | "eastmoney" | "tushare" | "mixed"
export type InstrumentStatus = "listed" | "suspended" | "delisted" | "unknown"
export type IntradaySeries = { tradeDate: string; points: MinutePoint[]; freshness: Freshness; warnings?: WarningCode[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KlinePageResult = { added: number; hasMore: boolean }
/**
 * Spec: quotes-module.md §2
 */
export type KlinePeriod = "day" | "week" | "month"
export type KlinePoint = { date: string; open: Price; close: Price; high: Price; low: Price; volume?: Volume | null; amount?: Amount | null }
export type KlineSeries = { period: KlinePeriod; adjust: Adjust; points: KlinePoint[]; freshness: Freshness; warnings?: WarningCode[] }
export type ListMarketItem = ({ tsCode: TsCode; name: string; category: InstrumentCategory; market: Market; board?: string | null; sector?: string | null; status?: InstrumentStatus | null; isSt?: boolean | null; publisher?: string | null; indexCategory?: string | null; fundType?: string | null; management?: string | null; listDate?: string | null; source: InstrumentSource; updatedAt: string }) & { quote?: ListMarketQuoteSummary | null; quoteFreshness?: Freshness | null; warnings?: WarningCode[] }
export type ListMarketPage = { limit: number; offset: number; hasMore: boolean }
export type ListMarketQuoteSummary = { tradeDate?: string | null; price?: number | null; change?: number | null; changePercent?: number | null; open?: number | null; high?: number | null; low?: number | null; previousClose?: number | null; volume?: number | null; amount?: number | null }
export type ListMarketRequest = { category?: InstrumentCategory | null; query?: string | null; includeQuote?: boolean | null; limit?: number | null; offset?: number | null }
export type ListMarketResponse = { items: ListMarketItem[]; page: ListMarketPage }
export type ListNewsSourcesResponse = { items: NewsSource[] }
export type MarkTriggerHandledRequest = { triggerId: string; reason: string }
export type MarkTriggerHandledResponse = { accepted: boolean; trigger?: AccountTrigger | null; accountEventIds?: string[]; reason?: ErrorCode | null; message?: string | null }
export type Market = "SH" | "SZ" | "BJ"
/**
 * Spec: quotes-module.md §4 `market_breadth`。
 * 
 * 全市场宽度统计；按 spec 只统计 `category == stock`（不含指数、基金）。
 * 计算前必须先用 quote 有效性规则筛掉无可用 quote 或不匹配 eligible
 * trade date 的标的，这些归入 `no_data`。
 */
export type MarketBreadth = { 
/**
 * 有效 quote 的标的总数。`up + down + flat == total`。
 */
total: number; 
/**
 * `change_percent > 0` 的家数。
 */
up: number; 
/**
 * `change_percent < 0` 的家数。
 */
down: number; 
/**
 * `change_percent == 0`（或缺失但 quote 仍有效）的家数。
 */
flat: number; 
/**
 * 涨停家数（按本模块顶部阈值规则）。是 `up` 的子集。
 */
limitUp: number; 
/**
 * 跌停家数（按本模块顶部阈值规则）。是 `down` 的子集。
 */
limitDown: number; 
/**
 * universe 中没有有效 quote 的标的数（snapshot missing / expired / 非 stock category 不计入此数）。
 */
noData: number; 
/**
 * 本次统计使用的 eligible trade date。
 */
tradeDate: string; 
/**
 * 计算完成时间。
 */
computedAt: string }
export type MinuteKlinePeriod = "1m" | "5m" | "15m" | "30m" | "60m"
export type MinuteKlinePoint = { timestampMs: number; open: Price; close: Price; high: Price; low: Price; volume: Volume; amount: Amount }
export type MinuteKlineSeries = { period: MinuteKlinePeriod; points: MinuteKlinePoint[]; freshness: Freshness; warnings?: WarningCode[] }
export type MinutePoint = { tradeDate: string; time: string; price: Price; average?: Price | null; volume?: Volume | null; amount?: Amount | null }
/**
 * CNY，保留到分；内部计算可使用更高精度。
 */
export type Money = string
export type NewsDateCount = { date: string; count: number }
/**
 * 单 provider / source 失败（shared-types.md §6 NewsFailure）。
 */
export type NewsFailure = { provider: string; source?: string | null; code: ErrorCode; message?: string | null; details?: JsonValue | null; stage?: NewsRefreshStage | null; retryable?: boolean | null; occurredAt: string }
export type NewsItemFreshness = { ageMs?: number | null; articleFetchedAt?: string | null }
/**
 * 排序方向。默认语义 `Desc`（最新在前）。`Asc` 专供前端「往上滑加载更新」的
 * keyset 游标（升序取紧邻最新一条之上的一页，前端 reverse 后 prepend）。
 * 
 * Spec: news-module.md §4 fetch_news（`order` 语义 + 双向 keyset 读取）。
 */
export type NewsOrder = "desc" | "asc"
/**
 * Refresh stage（spec §4 / §5）。
 */
export type NewsRefreshStage = "fetch" | "normalize" | "save" | "article"
/**
 * 单条 item 跳过 / partial 提示（shared-types.md §6 NewsRefreshWarning）。
 */
export type NewsRefreshWarning = { provider: string; source?: string | null; code: WarningCode; message?: string | null; stage?: NewsRefreshStage | null; skippedCount?: number | null; occurredAt: string }
/**
 * `source_id` 由 `namespace:channel` 形式构成；与 `NewsItem.source` 完全一致。
 */
export type NewsSource = { sourceId: string; provider: string; displayName?: string | null; enabled: boolean; dynamic?: boolean | null; lastRefreshAt?: string | null; lastError?: NewsSourceLastError | null }
export type NewsSourceLastError = { code: ErrorCode; message?: string | null; occurredAt: string }
/**
 * Spec: account-module.md §2 订单模型
 */
export type Order = { orderId: string; tsCode: TsCode; side: OrderSide; orderType: OrderType; limitPrice?: Price | null; quantity: Shares; filledQuantity: Shares; status: OrderStatus; intent: OrderIntent; positionId?: string | null; reason?: string | null; actor: TradingActor; createdAt: string; updatedAt: string; expiresAt?: string | null }
export type OrderIntent = "open_position" | "scale_in" | "scale_out" | "close_position" | "direct_order"
export type OrderSide = "buy" | "sell"
export type OrderStatus = "pending" | "partially_filled" | "filled" | "cancelled" | "rejected" | "expired"
export type OrderType = "market" | "limit"
export type PingResult = { ok: boolean; message: string }
/**
 * Spec: account-module.md §2 仓位模型
 */
export type Position = { positionId: string; tsCode: TsCode; name: string; status: PositionStatus; quantity: Shares; sellableQuantity: Shares; avgCost: Price; marketPrice?: Price | null; marketValue?: Money | null; quoteFreshness?: Freshness | null; realizedPnl: Money; unrealizedPnl?: Money | null; openedAt: string; closedAt?: string | null; protection?: PositionProtection | null; actor: TradingActor; reasoning?: string | null; warnings?: WarningCode[] }
/**
 * Spec: account-module.md §2 保护条件模型
 */
export type PositionProtection = { stopLoss?: Price | null; takeProfit?: Price | null; timeStopAt?: string | null; invalidationSignals?: string[]; enabled: boolean; revision: number; updatedAt: string }
export type PositionStatus = "open" | "closed"
export type PositionStatusFilter = "open" | "closed" | "all"
/**
 * CNY / 股或份。
 */
export type Price = string
/**
 * 渠道视图 —— **屏蔽 apiKey 明文**，只回 `apiKeySet: bool`。
 * 
 * Spec §2：apiKey 只写不读；list / get DTO 必须屏蔽明文。
 */
export type ProviderChannelView = { channelId: string; provider: string; wireFormat: WireFormat; baseUrl?: string | null; model: string; enabled: boolean; isActive: boolean; 
/**
 * apiKey 是否已设置（永远不回传明文）。
 */
apiKeySet: boolean }
/**
 * Spec: quotes-module.md §2 行情 DTO
 */
export type QuoteDepthLevel = { price?: Price | null; volume?: Volume | null }
/**
 * Spec: quotes-module.md §2 行情 DTO
 */
export type QuoteSource = "tdx" | "eastmoney" | "tencent" | "sina" | "mixed"
/**
 * Response 级 / item 级错误条目。
 * 
 * Spec: docs/design/quotes-module.md §4 `ResponseError`；shared-types.md §5。
 * 跨 BC 复用（News / Account / Quotes 都可以返回）。
 */
export type ResponseError = { code: ErrorCode; message?: string | null; field?: string | null; tsCode?: TsCode | null }
export type ScanCondition = { field: ScanConditionField; op: ScanOp; value: ScanConditionValue }
export type ScanConditionField = "change_percent" | "amount" | "volume" | "turnover_rate" | "volume_ratio" | "pe_ttm" | "pb" | "total_mv" | "circ_mv"
export type ScanConditionValue = number | [number, number]
export type ScanCriteria = { filter?: string | null; conditions?: ScanCondition[] | null; sortBy?: string | null; limit: number }
export type ScanFilter = "limit_up" | "limit_down" | "top_gain" | "top_loss" | "top_amount" | "top_volume"
export type ScanItem = { rank: number; tsCode: TsCode; name?: string | null; category: InstrumentCategory; quote?: StockQuote | null; dailyBasic?: DailyBasic | null; warnings?: WarningCode[] }
export type ScanMarketRequest = { category?: InstrumentCategory | null; filter?: ScanFilter | null; conditions?: ScanCondition[] | null; sortBy?: ScanSortBy | null; limit?: number | null }
export type ScanMarketResponse = ({ generatedAt: string; universe: ScanUniverse; criteria: ScanCriteria; items: ScanItem[]; warnings?: WarningCode[] }) & { errors?: ResponseError[] }
export type ScanOp = "gt" | "gte" | "lt" | "lte" | "eq" | "between"
export type ScanSortBy = "change_pct_desc" | "change_pct_asc" | "amount_desc" | "volume_desc" | "turnover_rate_desc"
export type ScanUniverse = { category?: InstrumentCategory | null; total: number; validQuoteCount?: number | null; excludedMissingQuoteCount?: number | null; excludedExpiredQuoteCount?: number | null; matched: number }
/**
 * 股 / 份数量。
 * 
 * Spec: shared-types.md §2
 * - Account 写接口必须校验 `Shares` 为正数；股票和场内基金买卖数量必须是 100 股 / 份整数倍。
 * （正数 / 整手校验由 Account domain 实现，本类型仅承载数值。）
 */
export type Shares = number
/**
 * Tool 副作用分类（spec §2 `SideEffect`）。
 */
export type SideEffect = "none" | "non_trading_write" | "trading_write"
/**
 * Spec: quotes-module.md §2 — fetch_data profile 投影。
 */
export type StockProfile = { tsCode: TsCode; name: string; category: InstrumentCategory; market: Market; board?: string | null; sector?: string | null; status?: InstrumentStatus | null; isSt?: boolean | null; listDate?: string | null }
/**
 * Spec: quotes-module.md §2 StockQuote
 */
export type StockQuote = { tsCode: TsCode; name?: string | null; category: InstrumentCategory; tradeDate: string; price?: Price | null; previousClose?: Price | null; open?: Price | null; high?: Price | null; low?: Price | null; change?: Price | null; changePercent?: number | null; volume?: Volume | null; amount?: Amount | null; turnoverRate?: number | null; volumeRatio?: number | null; limitUp?: Price | null; limitDown?: Price | null; bid?: QuoteDepthLevel[]; ask?: QuoteDepthLevel[]; tradeStatus: TradeStatus; source: QuoteSource; capturedAt: string; exchangeTime?: string | null; freshness: Freshness; warnings?: WarningCode[] }
/**
 * 一个 Tool 的协议描述。
 * 
 * Spec: agent-infra-module.md §2 `ToolSpec`
 * 
 * 规则（来自 spec §2）：
 * - 同名 tool 只能注册一次；重复注册必须 fail closed。
 * - `examples` 至少 1 个完整 `<use_tool ...>{...}</use_tool>` 示例字符串。
 * - description 应当能被产品负责人手写为 markdown。
 */
export type ToolSpec = { name: string; description: string; 
/**
 * JSON Schema（dispatch 前校验）。
 */
inputSchema: JsonValue; examples: string[]; sideEffect: SideEffect; timeoutMs: number }
/**
 * Spec: quotes-module.md §2 — query facade 派生 trade status。
 */
export type TradeStatus = "trading" | "halted" | "closed" | "unknown"
/**
 * Trading actor — 当前订单 / 仓位只能由 `agent` 发起。
 * 
 * Spec: account-module.md §2 actor 命名规则。
 */
export type TradingActor = "agent"
export type TriggerHandledAll = "all"
export type TriggerHandledFilter = boolean | TriggerHandledAll
/**
 * 跨模块主键。格式：6 位数字 + `.` + 市场后缀（`600519.SH` / `000001.SZ` / `430047.BJ`）。
 * 
 * Spec: shared-types.md §1
 * - 匹配大小写不敏感，但对外返回必须大写。
 * - 非 `TsCode` 标识不能作为跨模块持久化主键。
 */
export type TsCode = string
/**
 * 编辑已有渠道的请求 —— 按 channelId 更新可编辑字段。
 * 
 * Spec §5 前端命令：`agent_update_channel`。apiKey 为空/省略 = 保留原 key 不变；
 * 不修改 is_active；未暴露的能力字段（thinking budget 等）保留原值。
 */
export type UpdateChannelInput = { channelId: string; provider: string; wireFormat: WireFormat; baseUrl?: string | null; model: string; 
/**
 * 空/省略 = 保留原 key；非空才覆盖。
 */
apiKey?: string | null; enabled?: boolean | null; supportsVision?: boolean | null; supportsThinking?: boolean | null; maxOutputTokens?: number | null; contextWindowTokens?: number | null }
export type UpdateWatchlistRequest = ({ action: "add"; ts_code: TsCode; note?: string | null; reason?: string | null } | { action: "remove"; ts_code: TsCode; reason?: string | null } | { action: "update_note"; ts_code: TsCode; note?: string | null; reason?: string | null })
export type UpdateWatchlistResponse = { accepted: boolean; reason?: ErrorCode | null; message?: string | null; item?: WatchlistItem | null; accountEventIds: string[]; warnings?: WarningCode[] }
/**
 * 成交量，股或份。Provider 单位必须 normalize 到最小交易数量单位，不使用"手"。
 */
export type Volume = number
export type WarmArticlesErr = { ok: false; error: WarmArticlesError }
/**
 * `warm_articles` 失败 error（spec §5）。
 */
export type WarmArticlesError = { code: ErrorCode; field?: WarmArticlesErrorField | null; message?: string | null }
export type WarmArticlesErrorField = "newsIds" | "recentLimit"
export type WarmArticlesOk = { ok: true; result: WarmArticlesResult }
export type WarmArticlesRequest = { newsIds?: string[] | null; recentLimit?: number | null; force?: boolean | null }
export type WarmArticlesResponse = WarmArticlesOk | WarmArticlesErr
export type WarmArticlesResult = { batchId: string; requestedCount: number; attemptedCount: number; articleUpdatedCount: number; articleUpdatedNewsIds: string[]; warnings: NewsRefreshWarning[]; failures: NewsFailure[] }
export type WarningCode = "quote_missing" | "quote_stale" | "snapshot_expired" | "quote_price_missing" | "depth_missing" | "instrument_missing" | "provider_partial_failure" | "article_missing" | "qfq_missing" | "using_unadjusted_kline" | "daily_basic_missing" | "events_missing" | "strategy_omitted" | "mapping_missing" | "data_partial"
/**
 * Spec: account-module.md §2 自选模型
 */
export type WatchlistItem = { tsCode: TsCode; name?: string | null; addedAt: string; note?: string | null }
/**
 * 自选展示模型：WatchlistItem + 可选 quote。
 * 
 * Spec: account-module.md §4 fetch_account.include.watchlist
 */
export type WatchlistItemView = ({ tsCode: TsCode; name?: string | null; addedAt: string; note?: string | null }) & { quote?: WatchlistQuoteView | null }
/**
 * 自选行情字段。来自 Quotes snapshot；不存在时 freshness = missing。
 * 
 * Spec: account-module.md §4 (fetch_account watchlist quote 字段)
 */
export type WatchlistQuoteView = { price?: Price | null; changePercent?: number | null; volume?: Volume | null; amount?: Amount | null; source?: string | null; freshness?: Freshness | null }
/**
 * Wire format 标识 — channel adapter 选择哪个 provider 实现。
 */
export type WireFormat = 
/**
 * Anthropic `/v1/messages`
 */
"messages" | 
/**
 * OpenAI `/v1/responses`
 */
"responses" | 
/**
 * OpenAI-compatible `/v1/chat/completions`
 */
"chat_completions"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
